/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Side } from './Side';
import {
    SideFromJSON,
    SideFromJSONTyped,
    SideToJSON,
} from './Side';
import type { ForceUnit } from './ForceUnit';
import {
    ForceUnitFromJSON,
    ForceUnitFromJSONTyped,
    ForceUnitToJSON,
} from './ForceUnit';

/**
 * 
 * @export
 * @interface A500RepDataPointData
 */
export interface A500RepDataPointData {
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    id: number;
    /**
     * 
     * @type {Side}
     * @memberof A500RepDataPointData
     */
    side: Side;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    work: number;
    /**
     * 
     * @type {Date}
     * @memberof A500RepDataPointData
     */
    completedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    reactionTime: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    peakPower: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    averagePower: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    peakVelocity: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    averageVelocity: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    rangeOfMotion: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    setPointForce: number;
    /**
     * 
     * @type {ForceUnit}
     * @memberof A500RepDataPointData
     */
    forceUnit: ForceUnit;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    startSinceEpoch: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    endSinceEpoch: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    addedMass: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    addedForce: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    peakTorque?: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    averageTorque?: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    peakForce?: number;
    /**
     * 
     * @type {number}
     * @memberof A500RepDataPointData
     */
    averageForce?: number;
}

/**
 * Check if a given object implements the A500RepDataPointData interface.
 */
export function instanceOfA500RepDataPointData(value: object): value is A500RepDataPointData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('side' in value) || value['side'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('work' in value) || value['work'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('reactionTime' in value) || value['reactionTime'] === undefined) return false;
    if (!('peakPower' in value) || value['peakPower'] === undefined) return false;
    if (!('averagePower' in value) || value['averagePower'] === undefined) return false;
    if (!('peakVelocity' in value) || value['peakVelocity'] === undefined) return false;
    if (!('averageVelocity' in value) || value['averageVelocity'] === undefined) return false;
    if (!('rangeOfMotion' in value) || value['rangeOfMotion'] === undefined) return false;
    if (!('setPointForce' in value) || value['setPointForce'] === undefined) return false;
    if (!('forceUnit' in value) || value['forceUnit'] === undefined) return false;
    if (!('startSinceEpoch' in value) || value['startSinceEpoch'] === undefined) return false;
    if (!('endSinceEpoch' in value) || value['endSinceEpoch'] === undefined) return false;
    if (!('addedMass' in value) || value['addedMass'] === undefined) return false;
    if (!('addedForce' in value) || value['addedForce'] === undefined) return false;
    return true;
}

export function A500RepDataPointDataFromJSON(json: any): A500RepDataPointData {
    return A500RepDataPointDataFromJSONTyped(json, false);
}

export function A500RepDataPointDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): A500RepDataPointData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'side': SideFromJSON(json['side']),
        'count': json['count'],
        'work': json['work'],
        'completedAt': (new Date(json['completedAt'])),
        'reactionTime': json['reactionTime'],
        'peakPower': json['peakPower'],
        'averagePower': json['averagePower'],
        'peakVelocity': json['peakVelocity'],
        'averageVelocity': json['averageVelocity'],
        'rangeOfMotion': json['rangeOfMotion'],
        'setPointForce': json['setPointForce'],
        'forceUnit': ForceUnitFromJSON(json['forceUnit']),
        'startSinceEpoch': json['startSinceEpoch'],
        'endSinceEpoch': json['endSinceEpoch'],
        'addedMass': json['addedMass'],
        'addedForce': json['addedForce'],
        'peakTorque': json['peakTorque'] == null ? undefined : json['peakTorque'],
        'averageTorque': json['averageTorque'] == null ? undefined : json['averageTorque'],
        'peakForce': json['peakForce'] == null ? undefined : json['peakForce'],
        'averageForce': json['averageForce'] == null ? undefined : json['averageForce'],
    };
}

export function A500RepDataPointDataToJSON(value?: A500RepDataPointData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'side': SideToJSON(value['side']),
        'count': value['count'],
        'work': value['work'],
        'completedAt': ((value['completedAt']).toISOString()),
        'reactionTime': value['reactionTime'],
        'peakPower': value['peakPower'],
        'averagePower': value['averagePower'],
        'peakVelocity': value['peakVelocity'],
        'averageVelocity': value['averageVelocity'],
        'rangeOfMotion': value['rangeOfMotion'],
        'setPointForce': value['setPointForce'],
        'forceUnit': ForceUnitToJSON(value['forceUnit']),
        'startSinceEpoch': value['startSinceEpoch'],
        'endSinceEpoch': value['endSinceEpoch'],
        'addedMass': value['addedMass'],
        'addedForce': value['addedForce'],
        'peakTorque': value['peakTorque'],
        'averageTorque': value['averageTorque'],
        'peakForce': value['peakForce'],
        'averageForce': value['averageForce'],
    };
}

