/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const A500AppType = {
    performance: 'performance',
    elder: 'elder',
    medical: 'medical',
    commercial: 'commercial'
} as const;
export type A500AppType =
        | 'performance' 
        | 'elder' 
        | 'medical' 
        | 'commercial' 
;


export function instanceOfA500AppType(value: unknown): boolean {
    return (Object.values(A500AppType) as unknown[]).includes(value);
}

export function A500AppTypeFromJSON(json: unknown): A500AppType {
    return A500AppTypeFromJSONTyped(json, false);
}

export function A500AppTypeFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): A500AppType {
    return json as A500AppType;
}

export function A500AppTypeToJSON(value?: A500AppType | null): A500AppType | null | undefined {
    return value;
}

