/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyCompositionMeasurementData
 */
export interface BodyCompositionMeasurementData {
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    totalBodyWater?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    intracellularWater?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    extracellularWater?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    extracellularWaterToTotalBodyWaterRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    dryLeanMass?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMass?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMass?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    skeletalMuscleMass?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyMassIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    visceralFatLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    basalMetabolicRate?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassOfRightArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassPercentageOfRightArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassOfLeftArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassPercentageOfLeftArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassOfTrunk?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassPercentageOfTrunk?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassOfRightLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassPercentageOfRightLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassOfLeftLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    leanBodyMassPercentageOfLeftLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassOfRightArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassPercentageOfRightArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassOfLeftArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassPercentageOfLeftArm?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassOfTrunk?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassPercentageOfTrunk?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassOfRightLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassPercentageOfRightLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassOfLeftLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCompositionMeasurementData
     */
    bodyFatMassPercentageOfLeftLeg?: number;
}

/**
 * Check if a given object implements the BodyCompositionMeasurementData interface.
 */
export function instanceOfBodyCompositionMeasurementData(value: object): value is BodyCompositionMeasurementData {
    return true;
}

export function BodyCompositionMeasurementDataFromJSON(json: any): BodyCompositionMeasurementData {
    return BodyCompositionMeasurementDataFromJSONTyped(json, false);
}

export function BodyCompositionMeasurementDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCompositionMeasurementData {
    if (json == null) {
        return json;
    }
    return {
        
        'totalBodyWater': json['totalBodyWater'] == null ? undefined : json['totalBodyWater'],
        'intracellularWater': json['intracellularWater'] == null ? undefined : json['intracellularWater'],
        'extracellularWater': json['extracellularWater'] == null ? undefined : json['extracellularWater'],
        'extracellularWaterToTotalBodyWaterRatio': json['extracellularWaterToTotalBodyWaterRatio'] == null ? undefined : json['extracellularWaterToTotalBodyWaterRatio'],
        'dryLeanMass': json['dryLeanMass'] == null ? undefined : json['dryLeanMass'],
        'bodyFatMass': json['bodyFatMass'] == null ? undefined : json['bodyFatMass'],
        'leanBodyMass': json['leanBodyMass'] == null ? undefined : json['leanBodyMass'],
        'skeletalMuscleMass': json['skeletalMuscleMass'] == null ? undefined : json['skeletalMuscleMass'],
        'bodyMassIndex': json['bodyMassIndex'] == null ? undefined : json['bodyMassIndex'],
        'visceralFatLevel': json['visceralFatLevel'] == null ? undefined : json['visceralFatLevel'],
        'basalMetabolicRate': json['basalMetabolicRate'] == null ? undefined : json['basalMetabolicRate'],
        'leanBodyMassOfRightArm': json['leanBodyMassOfRightArm'] == null ? undefined : json['leanBodyMassOfRightArm'],
        'leanBodyMassPercentageOfRightArm': json['leanBodyMassPercentageOfRightArm'] == null ? undefined : json['leanBodyMassPercentageOfRightArm'],
        'leanBodyMassOfLeftArm': json['leanBodyMassOfLeftArm'] == null ? undefined : json['leanBodyMassOfLeftArm'],
        'leanBodyMassPercentageOfLeftArm': json['leanBodyMassPercentageOfLeftArm'] == null ? undefined : json['leanBodyMassPercentageOfLeftArm'],
        'leanBodyMassOfTrunk': json['leanBodyMassOfTrunk'] == null ? undefined : json['leanBodyMassOfTrunk'],
        'leanBodyMassPercentageOfTrunk': json['leanBodyMassPercentageOfTrunk'] == null ? undefined : json['leanBodyMassPercentageOfTrunk'],
        'leanBodyMassOfRightLeg': json['leanBodyMassOfRightLeg'] == null ? undefined : json['leanBodyMassOfRightLeg'],
        'leanBodyMassPercentageOfRightLeg': json['leanBodyMassPercentageOfRightLeg'] == null ? undefined : json['leanBodyMassPercentageOfRightLeg'],
        'leanBodyMassOfLeftLeg': json['leanBodyMassOfLeftLeg'] == null ? undefined : json['leanBodyMassOfLeftLeg'],
        'leanBodyMassPercentageOfLeftLeg': json['leanBodyMassPercentageOfLeftLeg'] == null ? undefined : json['leanBodyMassPercentageOfLeftLeg'],
        'bodyFatMassOfRightArm': json['bodyFatMassOfRightArm'] == null ? undefined : json['bodyFatMassOfRightArm'],
        'bodyFatMassPercentageOfRightArm': json['bodyFatMassPercentageOfRightArm'] == null ? undefined : json['bodyFatMassPercentageOfRightArm'],
        'bodyFatMassOfLeftArm': json['bodyFatMassOfLeftArm'] == null ? undefined : json['bodyFatMassOfLeftArm'],
        'bodyFatMassPercentageOfLeftArm': json['bodyFatMassPercentageOfLeftArm'] == null ? undefined : json['bodyFatMassPercentageOfLeftArm'],
        'bodyFatMassOfTrunk': json['bodyFatMassOfTrunk'] == null ? undefined : json['bodyFatMassOfTrunk'],
        'bodyFatMassPercentageOfTrunk': json['bodyFatMassPercentageOfTrunk'] == null ? undefined : json['bodyFatMassPercentageOfTrunk'],
        'bodyFatMassOfRightLeg': json['bodyFatMassOfRightLeg'] == null ? undefined : json['bodyFatMassOfRightLeg'],
        'bodyFatMassPercentageOfRightLeg': json['bodyFatMassPercentageOfRightLeg'] == null ? undefined : json['bodyFatMassPercentageOfRightLeg'],
        'bodyFatMassOfLeftLeg': json['bodyFatMassOfLeftLeg'] == null ? undefined : json['bodyFatMassOfLeftLeg'],
        'bodyFatMassPercentageOfLeftLeg': json['bodyFatMassPercentageOfLeftLeg'] == null ? undefined : json['bodyFatMassPercentageOfLeftLeg'],
    };
}

export function BodyCompositionMeasurementDataToJSON(value?: BodyCompositionMeasurementData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalBodyWater': value['totalBodyWater'],
        'intracellularWater': value['intracellularWater'],
        'extracellularWater': value['extracellularWater'],
        'extracellularWaterToTotalBodyWaterRatio': value['extracellularWaterToTotalBodyWaterRatio'],
        'dryLeanMass': value['dryLeanMass'],
        'bodyFatMass': value['bodyFatMass'],
        'leanBodyMass': value['leanBodyMass'],
        'skeletalMuscleMass': value['skeletalMuscleMass'],
        'bodyMassIndex': value['bodyMassIndex'],
        'visceralFatLevel': value['visceralFatLevel'],
        'basalMetabolicRate': value['basalMetabolicRate'],
        'leanBodyMassOfRightArm': value['leanBodyMassOfRightArm'],
        'leanBodyMassPercentageOfRightArm': value['leanBodyMassPercentageOfRightArm'],
        'leanBodyMassOfLeftArm': value['leanBodyMassOfLeftArm'],
        'leanBodyMassPercentageOfLeftArm': value['leanBodyMassPercentageOfLeftArm'],
        'leanBodyMassOfTrunk': value['leanBodyMassOfTrunk'],
        'leanBodyMassPercentageOfTrunk': value['leanBodyMassPercentageOfTrunk'],
        'leanBodyMassOfRightLeg': value['leanBodyMassOfRightLeg'],
        'leanBodyMassPercentageOfRightLeg': value['leanBodyMassPercentageOfRightLeg'],
        'leanBodyMassOfLeftLeg': value['leanBodyMassOfLeftLeg'],
        'leanBodyMassPercentageOfLeftLeg': value['leanBodyMassPercentageOfLeftLeg'],
        'bodyFatMassOfRightArm': value['bodyFatMassOfRightArm'],
        'bodyFatMassPercentageOfRightArm': value['bodyFatMassPercentageOfRightArm'],
        'bodyFatMassOfLeftArm': value['bodyFatMassOfLeftArm'],
        'bodyFatMassPercentageOfLeftArm': value['bodyFatMassPercentageOfLeftArm'],
        'bodyFatMassOfTrunk': value['bodyFatMassOfTrunk'],
        'bodyFatMassPercentageOfTrunk': value['bodyFatMassPercentageOfTrunk'],
        'bodyFatMassOfRightLeg': value['bodyFatMassOfRightLeg'],
        'bodyFatMassPercentageOfRightLeg': value['bodyFatMassPercentageOfRightLeg'],
        'bodyFatMassOfLeftLeg': value['bodyFatMassOfLeftLeg'],
        'bodyFatMassPercentageOfLeftLeg': value['bodyFatMassPercentageOfLeftLeg'],
    };
}

