/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MuscleSorting } from './MuscleSorting';
import {
    MuscleSortingFromJSON,
    MuscleSortingFromJSONTyped,
    MuscleSortingToJSON,
} from './MuscleSorting';
import type { MuscleTargetLevel } from './MuscleTargetLevel';
import {
    MuscleTargetLevelFromJSON,
    MuscleTargetLevelFromJSONTyped,
    MuscleTargetLevelToJSON,
} from './MuscleTargetLevel';

/**
 * 
 * @export
 * @interface CardioExerciseMuscleListResponseMeta
 */
export interface CardioExerciseMuscleListResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    cardioExerciseId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    muscle?: string;
    /**
     * 
     * @type {MuscleTargetLevel}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    targetLevel?: MuscleTargetLevel;
    /**
     * 
     * @type {MuscleSorting}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    sort: MuscleSorting;
    /**
     * 
     * @type {boolean}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof CardioExerciseMuscleListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the CardioExerciseMuscleListResponseMeta interface.
 */
export function instanceOfCardioExerciseMuscleListResponseMeta(value: object): value is CardioExerciseMuscleListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function CardioExerciseMuscleListResponseMetaFromJSON(json: any): CardioExerciseMuscleListResponseMeta {
    return CardioExerciseMuscleListResponseMetaFromJSONTyped(json, false);
}

export function CardioExerciseMuscleListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardioExerciseMuscleListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'cardioExerciseId': json['cardioExerciseId'] == null ? undefined : json['cardioExerciseId'],
        'muscle': json['muscle'] == null ? undefined : json['muscle'],
        'targetLevel': json['targetLevel'] == null ? undefined : MuscleTargetLevelFromJSON(json['targetLevel']),
        'sort': MuscleSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function CardioExerciseMuscleListResponseMetaToJSON(value?: CardioExerciseMuscleListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cardioExerciseId': value['cardioExerciseId'],
        'muscle': value['muscle'],
        'targetLevel': MuscleTargetLevelToJSON(value['targetLevel']),
        'sort': MuscleSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

