/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const DevelopmentAccountRelationshipSorting = {
    id: 'id',
    userId: 'userId',
    role: 'role'
} as const;
export type DevelopmentAccountRelationshipSorting =
        | 'id' 
        | 'userId' 
        | 'role' 
;


export function instanceOfDevelopmentAccountRelationshipSorting(value: unknown): boolean {
    return (Object.values(DevelopmentAccountRelationshipSorting) as unknown[]).includes(value);
}

export function DevelopmentAccountRelationshipSortingFromJSON(json: unknown): DevelopmentAccountRelationshipSorting {
    return DevelopmentAccountRelationshipSortingFromJSONTyped(json, false);
}

export function DevelopmentAccountRelationshipSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): DevelopmentAccountRelationshipSorting {
    return json as DevelopmentAccountRelationshipSorting;
}

export function DevelopmentAccountRelationshipSortingToJSON(value?: DevelopmentAccountRelationshipSorting | null): DevelopmentAccountRelationshipSorting | null | undefined {
    return value;
}

