/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DevelopmentAccountRelationshipSorting } from './DevelopmentAccountRelationshipSorting';
import {
    DevelopmentAccountRelationshipSortingFromJSON,
    DevelopmentAccountRelationshipSortingFromJSONTyped,
    DevelopmentAccountRelationshipSortingToJSON,
} from './DevelopmentAccountRelationshipSorting';

/**
 * 
 * @export
 * @interface DevelopmentAccountRelationshipListResponseMeta
 */
export interface DevelopmentAccountRelationshipListResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof DevelopmentAccountRelationshipListResponseMeta
     */
    developmentAccountId: number;
    /**
     * 
     * @type {DevelopmentAccountRelationshipSorting}
     * @memberof DevelopmentAccountRelationshipListResponseMeta
     */
    sort: DevelopmentAccountRelationshipSorting;
    /**
     * 
     * @type {boolean}
     * @memberof DevelopmentAccountRelationshipListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DevelopmentAccountRelationshipListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof DevelopmentAccountRelationshipListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof DevelopmentAccountRelationshipListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the DevelopmentAccountRelationshipListResponseMeta interface.
 */
export function instanceOfDevelopmentAccountRelationshipListResponseMeta(value: object): value is DevelopmentAccountRelationshipListResponseMeta {
    if (!('developmentAccountId' in value) || value['developmentAccountId'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function DevelopmentAccountRelationshipListResponseMetaFromJSON(json: any): DevelopmentAccountRelationshipListResponseMeta {
    return DevelopmentAccountRelationshipListResponseMetaFromJSONTyped(json, false);
}

export function DevelopmentAccountRelationshipListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevelopmentAccountRelationshipListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'developmentAccountId': json['developmentAccountId'],
        'sort': DevelopmentAccountRelationshipSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function DevelopmentAccountRelationshipListResponseMetaToJSON(value?: DevelopmentAccountRelationshipListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'developmentAccountId': value['developmentAccountId'],
        'sort': DevelopmentAccountRelationshipSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

