/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const DisplayFocusMode = {
    mean: 'mean',
    peak: 'peak'
} as const;
export type DisplayFocusMode =
        | 'mean' 
        | 'peak' 
;


export function instanceOfDisplayFocusMode(value: unknown): boolean {
    return (Object.values(DisplayFocusMode) as unknown[]).includes(value);
}

export function DisplayFocusModeFromJSON(json: unknown): DisplayFocusMode {
    return DisplayFocusModeFromJSONTyped(json, false);
}

export function DisplayFocusModeFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): DisplayFocusMode {
    return json as DisplayFocusMode;
}

export function DisplayFocusModeToJSON(value?: DisplayFocusMode | null): DisplayFocusMode | null | undefined {
    return value;
}

