/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailAddressData } from './EmailAddressData';
import {
    EmailAddressDataFromJSON,
    EmailAddressDataFromJSONTyped,
    EmailAddressDataToJSON,
} from './EmailAddressData';

/**
 * 
 * @export
 * @interface EmailAddressResponse
 */
export interface EmailAddressResponse {
    /**
     * 
     * @type {EmailAddressData}
     * @memberof EmailAddressResponse
     */
    emailAddress: EmailAddressData;
    /**
     * 
     * @type {string}
     * @memberof EmailAddressResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAddressResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the EmailAddressResponse interface.
 */
export function instanceOfEmailAddressResponse(value: object): value is EmailAddressResponse {
    if (!('emailAddress' in value) || value['emailAddress'] === undefined) return false;
    return true;
}

export function EmailAddressResponseFromJSON(json: any): EmailAddressResponse {
    return EmailAddressResponseFromJSONTyped(json, false);
}

export function EmailAddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAddressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'emailAddress': EmailAddressDataFromJSON(json['emailAddress']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function EmailAddressResponseToJSON(value?: EmailAddressResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emailAddress': EmailAddressDataToJSON(value['emailAddress']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

