/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmailAddressData } from './EmailAddressData';
import {
    EmailAddressDataFromJSON,
    EmailAddressDataFromJSONTyped,
    EmailAddressDataToJSON,
} from './EmailAddressData';
import type { EmailAddressListResponseMeta } from './EmailAddressListResponseMeta';
import {
    EmailAddressListResponseMetaFromJSON,
    EmailAddressListResponseMetaFromJSONTyped,
    EmailAddressListResponseMetaToJSON,
} from './EmailAddressListResponseMeta';

/**
 * 
 * @export
 * @interface EmailAddressListResponse
 */
export interface EmailAddressListResponse {
    /**
     * 
     * @type {Array<EmailAddressData>}
     * @memberof EmailAddressListResponse
     */
    emailAddresses: Array<EmailAddressData>;
    /**
     * 
     * @type {EmailAddressListResponseMeta}
     * @memberof EmailAddressListResponse
     */
    emailAddressesMeta: EmailAddressListResponseMeta;
    /**
     * 
     * @type {string}
     * @memberof EmailAddressListResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAddressListResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the EmailAddressListResponse interface.
 */
export function instanceOfEmailAddressListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "emailAddresses" in value;
    isInstance = isInstance && "emailAddressesMeta" in value;

    return isInstance;
}

export function EmailAddressListResponseFromJSON(json: any): EmailAddressListResponse {
    return EmailAddressListResponseFromJSONTyped(json, false);
}

export function EmailAddressListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAddressListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailAddresses': ((json['emailAddresses'] as Array<any>).map(EmailAddressDataFromJSON)),
        'emailAddressesMeta': EmailAddressListResponseMetaFromJSON(json['emailAddressesMeta']),
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'refreshToken': !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
    };
}

export function EmailAddressListResponseToJSON(value?: EmailAddressListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailAddresses': ((value.emailAddresses as Array<any>).map(EmailAddressDataToJSON)),
        'emailAddressesMeta': EmailAddressListResponseMetaToJSON(value.emailAddressesMeta),
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
    };
}

