/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EmployeeRole = {
    Admin: 'admin',
    CustomerSupport: 'customerSupport',
    Trainer: 'trainer',
    FrontDesk: 'frontDesk',
    Maintenance: 'maintenance'
} as const;
export type EmployeeRole =
        | 'admin' 
        | 'customerSupport' 
        | 'trainer' 
        | 'frontDesk' 
        | 'maintenance' 
;


export function EmployeeRoleFromJSON(json: any): EmployeeRole {
    return EmployeeRoleFromJSONTyped(json, false);
}

export function EmployeeRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeRole {
    return json as EmployeeRole;
}

export function EmployeeRoleToJSON(value?: EmployeeRole | null): any {
    return value as any;
}

