/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorData
 */
export interface ErrorData {
    /**
     * 
     * @type {number}
     * @memberof ErrorData
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorData
     */
    explanation: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorData
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorData
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorData
     */
    status: number;
}

/**
 * Check if a given object implements the ErrorData interface.
 */
export function instanceOfErrorData(value: object): value is ErrorData {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('explanation' in value) || value['explanation'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ErrorDataFromJSON(json: any): ErrorData {
    return ErrorDataFromJSONTyped(json, false);
}

export function ErrorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorData {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'explanation': json['explanation'],
        'message': json['message'],
        'name': json['name'],
        'status': json['status'],
    };
}

export function ErrorDataToJSON(value?: ErrorData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'explanation': value['explanation'],
        'message': value['message'],
        'name': value['name'],
        'status': value['status'],
    };
}

