/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExerciseOrdinalSetAssignmentSorting } from './ExerciseOrdinalSetAssignmentSorting';
import {
    ExerciseOrdinalSetAssignmentSortingFromJSON,
    ExerciseOrdinalSetAssignmentSortingFromJSONTyped,
    ExerciseOrdinalSetAssignmentSortingToJSON,
} from './ExerciseOrdinalSetAssignmentSorting';

/**
 * 
 * @export
 * @interface ExerciseOrdinalSetAssignmentListResponseMeta
 */
export interface ExerciseOrdinalSetAssignmentListResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof ExerciseOrdinalSetAssignmentListResponseMeta
     */
    exerciseOrdinalSetId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOrdinalSetAssignmentListResponseMeta
     */
    ordinalIdentifier?: string;
    /**
     * 
     * @type {ExerciseOrdinalSetAssignmentSorting}
     * @memberof ExerciseOrdinalSetAssignmentListResponseMeta
     */
    sort: ExerciseOrdinalSetAssignmentSorting;
    /**
     * 
     * @type {boolean}
     * @memberof ExerciseOrdinalSetAssignmentListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ExerciseOrdinalSetAssignmentListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseOrdinalSetAssignmentListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseOrdinalSetAssignmentListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the ExerciseOrdinalSetAssignmentListResponseMeta interface.
 */
export function instanceOfExerciseOrdinalSetAssignmentListResponseMeta(value: object): value is ExerciseOrdinalSetAssignmentListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function ExerciseOrdinalSetAssignmentListResponseMetaFromJSON(json: any): ExerciseOrdinalSetAssignmentListResponseMeta {
    return ExerciseOrdinalSetAssignmentListResponseMetaFromJSONTyped(json, false);
}

export function ExerciseOrdinalSetAssignmentListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseOrdinalSetAssignmentListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'exerciseOrdinalSetId': json['exerciseOrdinalSetId'] == null ? undefined : json['exerciseOrdinalSetId'],
        'ordinalIdentifier': json['ordinalIdentifier'] == null ? undefined : json['ordinalIdentifier'],
        'sort': ExerciseOrdinalSetAssignmentSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function ExerciseOrdinalSetAssignmentListResponseMetaToJSON(value?: ExerciseOrdinalSetAssignmentListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exerciseOrdinalSetId': value['exerciseOrdinalSetId'],
        'ordinalIdentifier': value['ordinalIdentifier'],
        'sort': ExerciseOrdinalSetAssignmentSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

