/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardioExerciseVariantData } from './CardioExerciseVariantData';
import {
    CardioExerciseVariantDataFromJSON,
    CardioExerciseVariantDataFromJSONTyped,
    CardioExerciseVariantDataToJSON,
} from './CardioExerciseVariantData';
import type { StretchExerciseVariantData } from './StretchExerciseVariantData';
import {
    StretchExerciseVariantDataFromJSON,
    StretchExerciseVariantDataFromJSONTyped,
    StretchExerciseVariantDataToJSON,
} from './StretchExerciseVariantData';
import type { ExerciseOrdinalSetData } from './ExerciseOrdinalSetData';
import {
    ExerciseOrdinalSetDataFromJSON,
    ExerciseOrdinalSetDataFromJSONTyped,
    ExerciseOrdinalSetDataToJSON,
} from './ExerciseOrdinalSetData';
import type { StrengthExerciseVariantData } from './StrengthExerciseVariantData';
import {
    StrengthExerciseVariantDataFromJSON,
    StrengthExerciseVariantDataFromJSONTyped,
    StrengthExerciseVariantDataToJSON,
} from './StrengthExerciseVariantData';

/**
 * 
 * @export
 * @interface ExerciseOrdinalSetAssignmentData
 */
export interface ExerciseOrdinalSetAssignmentData {
    /**
     * 
     * @type {number}
     * @memberof ExerciseOrdinalSetAssignmentData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOrdinalSetAssignmentData
     */
    ordinalIdentifier: string;
    /**
     * 
     * @type {ExerciseOrdinalSetData}
     * @memberof ExerciseOrdinalSetAssignmentData
     */
    exerciseOrdinalSet?: ExerciseOrdinalSetData;
    /**
     * 
     * @type {StrengthExerciseVariantData}
     * @memberof ExerciseOrdinalSetAssignmentData
     */
    strengthExerciseVariant?: StrengthExerciseVariantData;
    /**
     * 
     * @type {CardioExerciseVariantData}
     * @memberof ExerciseOrdinalSetAssignmentData
     */
    cardioExerciseVariant?: CardioExerciseVariantData;
    /**
     * 
     * @type {StretchExerciseVariantData}
     * @memberof ExerciseOrdinalSetAssignmentData
     */
    stretchExerciseVariant?: StretchExerciseVariantData;
}

/**
 * Check if a given object implements the ExerciseOrdinalSetAssignmentData interface.
 */
export function instanceOfExerciseOrdinalSetAssignmentData(value: object): value is ExerciseOrdinalSetAssignmentData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ordinalIdentifier' in value) || value['ordinalIdentifier'] === undefined) return false;
    return true;
}

export function ExerciseOrdinalSetAssignmentDataFromJSON(json: any): ExerciseOrdinalSetAssignmentData {
    return ExerciseOrdinalSetAssignmentDataFromJSONTyped(json, false);
}

export function ExerciseOrdinalSetAssignmentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseOrdinalSetAssignmentData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ordinalIdentifier': json['ordinalIdentifier'],
        'exerciseOrdinalSet': json['exerciseOrdinalSet'] == null ? undefined : ExerciseOrdinalSetDataFromJSON(json['exerciseOrdinalSet']),
        'strengthExerciseVariant': json['strengthExerciseVariant'] == null ? undefined : StrengthExerciseVariantDataFromJSON(json['strengthExerciseVariant']),
        'cardioExerciseVariant': json['cardioExerciseVariant'] == null ? undefined : CardioExerciseVariantDataFromJSON(json['cardioExerciseVariant']),
        'stretchExerciseVariant': json['stretchExerciseVariant'] == null ? undefined : StretchExerciseVariantDataFromJSON(json['stretchExerciseVariant']),
    };
}

export function ExerciseOrdinalSetAssignmentDataToJSON(value?: ExerciseOrdinalSetAssignmentData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'ordinalIdentifier': value['ordinalIdentifier'],
        'exerciseOrdinalSet': ExerciseOrdinalSetDataToJSON(value['exerciseOrdinalSet']),
        'strengthExerciseVariant': StrengthExerciseVariantDataToJSON(value['strengthExerciseVariant']),
        'cardioExerciseVariant': CardioExerciseVariantDataToJSON(value['cardioExerciseVariant']),
        'stretchExerciseVariant': StretchExerciseVariantDataToJSON(value['stretchExerciseVariant']),
    };
}

