/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExerciseOrdinalSetData } from './ExerciseOrdinalSetData';
import {
    ExerciseOrdinalSetDataFromJSON,
    ExerciseOrdinalSetDataFromJSONTyped,
    ExerciseOrdinalSetDataToJSON,
} from './ExerciseOrdinalSetData';

/**
 * 
 * @export
 * @interface ExerciseOrdinalSetResponse
 */
export interface ExerciseOrdinalSetResponse {
    /**
     * 
     * @type {ExerciseOrdinalSetData}
     * @memberof ExerciseOrdinalSetResponse
     */
    exerciseOrdinalSet: ExerciseOrdinalSetData;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOrdinalSetResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseOrdinalSetResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the ExerciseOrdinalSetResponse interface.
 */
export function instanceOfExerciseOrdinalSetResponse(value: object): value is ExerciseOrdinalSetResponse {
    if (!('exerciseOrdinalSet' in value) || value['exerciseOrdinalSet'] === undefined) return false;
    return true;
}

export function ExerciseOrdinalSetResponseFromJSON(json: any): ExerciseOrdinalSetResponse {
    return ExerciseOrdinalSetResponseFromJSONTyped(json, false);
}

export function ExerciseOrdinalSetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseOrdinalSetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'exerciseOrdinalSet': ExerciseOrdinalSetDataFromJSON(json['exerciseOrdinalSet']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function ExerciseOrdinalSetResponseToJSON(value?: ExerciseOrdinalSetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exerciseOrdinalSet': ExerciseOrdinalSetDataToJSON(value['exerciseOrdinalSet']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

