/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityStrengthMachineSorting } from './FacilityStrengthMachineSorting';
import {
    FacilityStrengthMachineSortingFromJSON,
    FacilityStrengthMachineSortingFromJSONTyped,
    FacilityStrengthMachineSortingToJSON,
} from './FacilityStrengthMachineSorting';

/**
 * 
 * @export
 * @interface FacilityStrengthMachineListResponseMeta
 */
export interface FacilityStrengthMachineListResponseMeta {
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    query?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    source?: string;
    /**
     * 
     * @type {FacilityStrengthMachineSorting}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    sort: FacilityStrengthMachineSorting;
    /**
     * 
     * @type {number}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    facilityId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof FacilityStrengthMachineListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the FacilityStrengthMachineListResponseMeta interface.
 */
export function instanceOfFacilityStrengthMachineListResponseMeta(value: object): value is FacilityStrengthMachineListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function FacilityStrengthMachineListResponseMetaFromJSON(json: any): FacilityStrengthMachineListResponseMeta {
    return FacilityStrengthMachineListResponseMetaFromJSONTyped(json, false);
}

export function FacilityStrengthMachineListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityStrengthMachineListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
        'model': json['model'] == null ? undefined : json['model'],
        'source': json['source'] == null ? undefined : json['source'],
        'sort': FacilityStrengthMachineSortingFromJSON(json['sort']),
        'facilityId': json['facilityId'] == null ? undefined : json['facilityId'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function FacilityStrengthMachineListResponseMetaToJSON(value?: FacilityStrengthMachineListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': value['query'],
        'model': value['model'],
        'source': value['source'],
        'sort': FacilityStrengthMachineSortingToJSON(value['sort']),
        'facilityId': value['facilityId'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

