/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityDisplayOperatingScheduleTime } from './FacilityDisplayOperatingScheduleTime';
import {
    FacilityDisplayOperatingScheduleTimeFromJSON,
    FacilityDisplayOperatingScheduleTimeFromJSONTyped,
    FacilityDisplayOperatingScheduleTimeToJSON,
} from './FacilityDisplayOperatingScheduleTime';

/**
 * 
 * @export
 * @interface FacilityDisplayOperatingScheduleEntry
 */
export interface FacilityDisplayOperatingScheduleEntry {
    /**
     * 
     * @type {FacilityDisplayOperatingScheduleTime}
     * @memberof FacilityDisplayOperatingScheduleEntry
     */
    wakeAt: FacilityDisplayOperatingScheduleTime;
    /**
     * 
     * @type {FacilityDisplayOperatingScheduleTime}
     * @memberof FacilityDisplayOperatingScheduleEntry
     */
    sleepAt: FacilityDisplayOperatingScheduleTime;
}

/**
 * Check if a given object implements the FacilityDisplayOperatingScheduleEntry interface.
 */
export function instanceOfFacilityDisplayOperatingScheduleEntry(value: object): value is FacilityDisplayOperatingScheduleEntry {
    if (!('wakeAt' in value) || value['wakeAt'] === undefined) return false;
    if (!('sleepAt' in value) || value['sleepAt'] === undefined) return false;
    return true;
}

export function FacilityDisplayOperatingScheduleEntryFromJSON(json: any): FacilityDisplayOperatingScheduleEntry {
    return FacilityDisplayOperatingScheduleEntryFromJSONTyped(json, false);
}

export function FacilityDisplayOperatingScheduleEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityDisplayOperatingScheduleEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'wakeAt': FacilityDisplayOperatingScheduleTimeFromJSON(json['wakeAt']),
        'sleepAt': FacilityDisplayOperatingScheduleTimeFromJSON(json['sleepAt']),
    };
}

export function FacilityDisplayOperatingScheduleEntryToJSON(value?: FacilityDisplayOperatingScheduleEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'wakeAt': FacilityDisplayOperatingScheduleTimeToJSON(value['wakeAt']),
        'sleepAt': FacilityDisplayOperatingScheduleTimeToJSON(value['sleepAt']),
    };
}

