/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityStrengthMachineMaintenanceRecordData } from './FacilityStrengthMachineMaintenanceRecordData';
import {
    FacilityStrengthMachineMaintenanceRecordDataFromJSON,
    FacilityStrengthMachineMaintenanceRecordDataFromJSONTyped,
    FacilityStrengthMachineMaintenanceRecordDataToJSON,
} from './FacilityStrengthMachineMaintenanceRecordData';

/**
 * 
 * @export
 * @interface FacilityStrengthMachineMaintenanceRecordResponse
 */
export interface FacilityStrengthMachineMaintenanceRecordResponse {
    /**
     * 
     * @type {FacilityStrengthMachineMaintenanceRecordData}
     * @memberof FacilityStrengthMachineMaintenanceRecordResponse
     */
    facilityStrengthMachineMaintenanceRecord: FacilityStrengthMachineMaintenanceRecordData;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineMaintenanceRecordResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineMaintenanceRecordResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the FacilityStrengthMachineMaintenanceRecordResponse interface.
 */
export function instanceOfFacilityStrengthMachineMaintenanceRecordResponse(value: object): value is FacilityStrengthMachineMaintenanceRecordResponse {
    if (!('facilityStrengthMachineMaintenanceRecord' in value) || value['facilityStrengthMachineMaintenanceRecord'] === undefined) return false;
    return true;
}

export function FacilityStrengthMachineMaintenanceRecordResponseFromJSON(json: any): FacilityStrengthMachineMaintenanceRecordResponse {
    return FacilityStrengthMachineMaintenanceRecordResponseFromJSONTyped(json, false);
}

export function FacilityStrengthMachineMaintenanceRecordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityStrengthMachineMaintenanceRecordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'facilityStrengthMachineMaintenanceRecord': FacilityStrengthMachineMaintenanceRecordDataFromJSON(json['facilityStrengthMachineMaintenanceRecord']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function FacilityStrengthMachineMaintenanceRecordResponseToJSON(value?: FacilityStrengthMachineMaintenanceRecordResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'facilityStrengthMachineMaintenanceRecord': FacilityStrengthMachineMaintenanceRecordDataToJSON(value['facilityStrengthMachineMaintenanceRecord']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

