/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityData } from './FacilityData';
import {
    FacilityDataFromJSON,
    FacilityDataFromJSONTyped,
    FacilityDataToJSON,
} from './FacilityData';

/**
 * 
 * @export
 * @interface FacilityResponse
 */
export interface FacilityResponse {
    /**
     * 
     * @type {FacilityData}
     * @memberof FacilityResponse
     */
    facility: FacilityData;
    /**
     * 
     * @type {string}
     * @memberof FacilityResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the FacilityResponse interface.
 */
export function instanceOfFacilityResponse(value: object): value is FacilityResponse {
    if (!('facility' in value) || value['facility'] === undefined) return false;
    return true;
}

export function FacilityResponseFromJSON(json: any): FacilityResponse {
    return FacilityResponseFromJSONTyped(json, false);
}

export function FacilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'facility': FacilityDataFromJSON(json['facility']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function FacilityResponseToJSON(value?: FacilityResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'facility': FacilityDataToJSON(value['facility']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

