/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityConfigurationData } from './FacilityConfigurationData';
import {
    FacilityConfigurationDataFromJSON,
    FacilityConfigurationDataFromJSONTyped,
    FacilityConfigurationDataToJSON,
} from './FacilityConfigurationData';

/**
 * 
 * @export
 * @interface FacilityConfigurationResponse
 */
export interface FacilityConfigurationResponse {
    /**
     * 
     * @type {FacilityConfigurationData}
     * @memberof FacilityConfigurationResponse
     */
    facilityConfiguration: FacilityConfigurationData;
    /**
     * 
     * @type {string}
     * @memberof FacilityConfigurationResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityConfigurationResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the FacilityConfigurationResponse interface.
 */
export function instanceOfFacilityConfigurationResponse(value: object): value is FacilityConfigurationResponse {
    if (!('facilityConfiguration' in value) || value['facilityConfiguration'] === undefined) return false;
    return true;
}

export function FacilityConfigurationResponseFromJSON(json: any): FacilityConfigurationResponse {
    return FacilityConfigurationResponseFromJSONTyped(json, false);
}

export function FacilityConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'facilityConfiguration': FacilityConfigurationDataFromJSON(json['facilityConfiguration']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function FacilityConfigurationResponseToJSON(value?: FacilityConfigurationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'facilityConfiguration': FacilityConfigurationDataToJSON(value['facilityConfiguration']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

