/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacilityRelationshipNovaStaffInviteResponse
 */
export interface FacilityRelationshipNovaStaffInviteResponse {
    /**
     * 
     * @type {number}
     * @memberof FacilityRelationshipNovaStaffInviteResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FacilityRelationshipNovaStaffInviteResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityRelationshipNovaStaffInviteResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the FacilityRelationshipNovaStaffInviteResponse interface.
 */
export function instanceOfFacilityRelationshipNovaStaffInviteResponse(value: object): value is FacilityRelationshipNovaStaffInviteResponse {
    return true;
}

export function FacilityRelationshipNovaStaffInviteResponseFromJSON(json: any): FacilityRelationshipNovaStaffInviteResponse {
    return FacilityRelationshipNovaStaffInviteResponseFromJSONTyped(json, false);
}

export function FacilityRelationshipNovaStaffInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityRelationshipNovaStaffInviteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function FacilityRelationshipNovaStaffInviteResponseToJSON(value?: FacilityRelationshipNovaStaffInviteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

