/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionSorting } from './SessionSorting';
import {
    SessionSortingFromJSON,
    SessionSortingFromJSONTyped,
    SessionSortingToJSON,
} from './SessionSorting';

/**
 * 
 * @export
 * @interface FacilitySessionListResponseMeta
 */
export interface FacilitySessionListResponseMeta {
    /**
     * 
     * @type {boolean}
     * @memberof FacilitySessionListResponseMeta
     */
    open?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FacilitySessionListResponseMeta
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof FacilitySessionListResponseMeta
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FacilitySessionListResponseMeta
     */
    to?: Date;
    /**
     * 
     * @type {SessionSorting}
     * @memberof FacilitySessionListResponseMeta
     */
    sort: SessionSorting;
    /**
     * 
     * @type {number}
     * @memberof FacilitySessionListResponseMeta
     */
    facilityId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FacilitySessionListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FacilitySessionListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof FacilitySessionListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof FacilitySessionListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the FacilitySessionListResponseMeta interface.
 */
export function instanceOfFacilitySessionListResponseMeta(value: object): value is FacilitySessionListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function FacilitySessionListResponseMetaFromJSON(json: any): FacilitySessionListResponseMeta {
    return FacilitySessionListResponseMetaFromJSONTyped(json, false);
}

export function FacilitySessionListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilitySessionListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'open': json['open'] == null ? undefined : json['open'],
        'name': json['name'] == null ? undefined : json['name'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'sort': SessionSortingFromJSON(json['sort']),
        'facilityId': json['facilityId'] == null ? undefined : json['facilityId'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function FacilitySessionListResponseMetaToJSON(value?: FacilitySessionListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'open': value['open'],
        'name': value['name'],
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
        'sort': SessionSortingToJSON(value['sort']),
        'facilityId': value['facilityId'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

