/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacilityStrengthMachineInitializerOTPTokenResponse
 */
export interface FacilityStrengthMachineInitializerOTPTokenResponse {
    /**
     * 
     * @type {Date}
     * @memberof FacilityStrengthMachineInitializerOTPTokenResponse
     */
    expiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineInitializerOTPTokenResponse
     */
    initializerToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineInitializerOTPTokenResponse
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FacilityStrengthMachineInitializerOTPTokenResponse
     */
    isEncrypted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineInitializerOTPTokenResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineInitializerOTPTokenResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the FacilityStrengthMachineInitializerOTPTokenResponse interface.
 */
export function instanceOfFacilityStrengthMachineInitializerOTPTokenResponse(value: object): value is FacilityStrengthMachineInitializerOTPTokenResponse {
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function FacilityStrengthMachineInitializerOTPTokenResponseFromJSON(json: any): FacilityStrengthMachineInitializerOTPTokenResponse {
    return FacilityStrengthMachineInitializerOTPTokenResponseFromJSONTyped(json, false);
}

export function FacilityStrengthMachineInitializerOTPTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityStrengthMachineInitializerOTPTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': (new Date(json['expiresAt'])),
        'initializerToken': json['initializerToken'] == null ? undefined : json['initializerToken'],
        'url': json['url'] == null ? undefined : json['url'],
        'isEncrypted': json['isEncrypted'] == null ? undefined : json['isEncrypted'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function FacilityStrengthMachineInitializerOTPTokenResponseToJSON(value?: FacilityStrengthMachineInitializerOTPTokenResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'expiresAt': ((value['expiresAt']).toISOString()),
        'initializerToken': value['initializerToken'],
        'url': value['url'],
        'isEncrypted': value['isEncrypted'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

