/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacilityDisplayOperatingScheduleTime
 */
export interface FacilityDisplayOperatingScheduleTime {
    /**
     * 
     * @type {number}
     * @memberof FacilityDisplayOperatingScheduleTime
     */
    hour: number;
    /**
     * 
     * @type {number}
     * @memberof FacilityDisplayOperatingScheduleTime
     */
    minute: number;
}

/**
 * Check if a given object implements the FacilityDisplayOperatingScheduleTime interface.
 */
export function instanceOfFacilityDisplayOperatingScheduleTime(value: object): value is FacilityDisplayOperatingScheduleTime {
    if (!('hour' in value) || value['hour'] === undefined) return false;
    if (!('minute' in value) || value['minute'] === undefined) return false;
    return true;
}

export function FacilityDisplayOperatingScheduleTimeFromJSON(json: any): FacilityDisplayOperatingScheduleTime {
    return FacilityDisplayOperatingScheduleTimeFromJSONTyped(json, false);
}

export function FacilityDisplayOperatingScheduleTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityDisplayOperatingScheduleTime {
    if (json == null) {
        return json;
    }
    return {
        
        'hour': json['hour'],
        'minute': json['minute'],
    };
}

export function FacilityDisplayOperatingScheduleTimeToJSON(value?: FacilityDisplayOperatingScheduleTime | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hour': value['hour'],
        'minute': value['minute'],
    };
}

