/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const FacilityStrengthMachineSorting = {
    id: 'id',
    model: 'model',
    name: 'name'
} as const;
export type FacilityStrengthMachineSorting =
        | 'id' 
        | 'model' 
        | 'name' 
;


export function instanceOfFacilityStrengthMachineSorting(value: unknown): boolean {
    return (Object.values(FacilityStrengthMachineSorting) as unknown[]).includes(value);
}

export function FacilityStrengthMachineSortingFromJSON(json: unknown): FacilityStrengthMachineSorting {
    return FacilityStrengthMachineSortingFromJSONTyped(json, false);
}

export function FacilityStrengthMachineSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): FacilityStrengthMachineSorting {
    return json as FacilityStrengthMachineSorting;
}

export function FacilityStrengthMachineSortingToJSON(value?: FacilityStrengthMachineSorting | null): FacilityStrengthMachineSorting | null | undefined {
    return value;
}

