/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityUserRelationshipListResponseMeta } from './FacilityUserRelationshipListResponseMeta';
import {
    FacilityUserRelationshipListResponseMetaFromJSON,
    FacilityUserRelationshipListResponseMetaFromJSONTyped,
    FacilityUserRelationshipListResponseMetaToJSON,
} from './FacilityUserRelationshipListResponseMeta';
import type { FacilityRelationshipData } from './FacilityRelationshipData';
import {
    FacilityRelationshipDataFromJSON,
    FacilityRelationshipDataFromJSONTyped,
    FacilityRelationshipDataToJSON,
} from './FacilityRelationshipData';

/**
 * 
 * @export
 * @interface FacilityUserRelationshipListResponse
 */
export interface FacilityUserRelationshipListResponse {
    /**
     * 
     * @type {Array<FacilityRelationshipData>}
     * @memberof FacilityUserRelationshipListResponse
     */
    facilityRelationships: Array<FacilityRelationshipData>;
    /**
     * 
     * @type {FacilityUserRelationshipListResponseMeta}
     * @memberof FacilityUserRelationshipListResponse
     */
    facilityRelationshipsMeta: FacilityUserRelationshipListResponseMeta;
    /**
     * 
     * @type {string}
     * @memberof FacilityUserRelationshipListResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityUserRelationshipListResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the FacilityUserRelationshipListResponse interface.
 */
export function instanceOfFacilityUserRelationshipListResponse(value: object): value is FacilityUserRelationshipListResponse {
    if (!('facilityRelationships' in value) || value['facilityRelationships'] === undefined) return false;
    if (!('facilityRelationshipsMeta' in value) || value['facilityRelationshipsMeta'] === undefined) return false;
    return true;
}

export function FacilityUserRelationshipListResponseFromJSON(json: any): FacilityUserRelationshipListResponse {
    return FacilityUserRelationshipListResponseFromJSONTyped(json, false);
}

export function FacilityUserRelationshipListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityUserRelationshipListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'facilityRelationships': ((json['facilityRelationships'] as Array<any>).map(FacilityRelationshipDataFromJSON)),
        'facilityRelationshipsMeta': FacilityUserRelationshipListResponseMetaFromJSON(json['facilityRelationshipsMeta']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function FacilityUserRelationshipListResponseToJSON(value?: FacilityUserRelationshipListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'facilityRelationships': ((value['facilityRelationships'] as Array<any>).map(FacilityRelationshipDataToJSON)),
        'facilityRelationshipsMeta': FacilityUserRelationshipListResponseMetaToJSON(value['facilityRelationshipsMeta']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

