/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityStrengthMachineConfigurationData } from './FacilityStrengthMachineConfigurationData';
import {
    FacilityStrengthMachineConfigurationDataFromJSON,
    FacilityStrengthMachineConfigurationDataFromJSONTyped,
    FacilityStrengthMachineConfigurationDataToJSON,
} from './FacilityStrengthMachineConfigurationData';

/**
 * 
 * @export
 * @interface FacilityStrengthMachineConfigurationResponse
 */
export interface FacilityStrengthMachineConfigurationResponse {
    /**
     * 
     * @type {FacilityStrengthMachineConfigurationData}
     * @memberof FacilityStrengthMachineConfigurationResponse
     */
    facilityStrengthMachineConfiguration: FacilityStrengthMachineConfigurationData;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineConfigurationResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FacilityStrengthMachineConfigurationResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the FacilityStrengthMachineConfigurationResponse interface.
 */
export function instanceOfFacilityStrengthMachineConfigurationResponse(value: object): value is FacilityStrengthMachineConfigurationResponse {
    if (!('facilityStrengthMachineConfiguration' in value) || value['facilityStrengthMachineConfiguration'] === undefined) return false;
    return true;
}

export function FacilityStrengthMachineConfigurationResponseFromJSON(json: any): FacilityStrengthMachineConfigurationResponse {
    return FacilityStrengthMachineConfigurationResponseFromJSONTyped(json, false);
}

export function FacilityStrengthMachineConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityStrengthMachineConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'facilityStrengthMachineConfiguration': FacilityStrengthMachineConfigurationDataFromJSON(json['facilityStrengthMachineConfiguration']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function FacilityStrengthMachineConfigurationResponseToJSON(value?: FacilityStrengthMachineConfigurationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'facilityStrengthMachineConfiguration': FacilityStrengthMachineConfigurationDataToJSON(value['facilityStrengthMachineConfiguration']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

