/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HeightMeasurementData
 */
export interface HeightMeasurementData {
    /**
     * 
     * @type {number}
     * @memberof HeightMeasurementData
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof HeightMeasurementData
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof HeightMeasurementData
     */
    source: string;
    /**
     * 
     * @type {Date}
     * @memberof HeightMeasurementData
     */
    takenAt: Date;
    /**
     * 
     * @type {number}
     * @memberof HeightMeasurementData
     */
    metricHeight: number;
}

/**
 * Check if a given object implements the HeightMeasurementData interface.
 */
export function instanceOfHeightMeasurementData(value: object): value is HeightMeasurementData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('takenAt' in value) || value['takenAt'] === undefined) return false;
    if (!('metricHeight' in value) || value['metricHeight'] === undefined) return false;
    return true;
}

export function HeightMeasurementDataFromJSON(json: any): HeightMeasurementData {
    return HeightMeasurementDataFromJSONTyped(json, false);
}

export function HeightMeasurementDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeightMeasurementData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'source': json['source'],
        'takenAt': (new Date(json['takenAt'])),
        'metricHeight': json['metricHeight'],
    };
}

export function HeightMeasurementDataToJSON(value?: HeightMeasurementData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'source': value['source'],
        'takenAt': ((value['takenAt']).toISOString()),
        'metricHeight': value['metricHeight'],
    };
}

