/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StrengthMachineLine } from './StrengthMachineLine';
import {
    StrengthMachineLineFromJSON,
    StrengthMachineLineFromJSONTyped,
    StrengthMachineLineToJSON,
} from './StrengthMachineLine';
import type { MachineClaimStatus } from './MachineClaimStatus';
import {
    MachineClaimStatusFromJSON,
    MachineClaimStatusFromJSONTyped,
    MachineClaimStatusToJSON,
} from './MachineClaimStatus';

/**
 * 
 * @export
 * @interface MachineClaimData
 */
export interface MachineClaimData {
    /**
     * 
     * @type {number}
     * @memberof MachineClaimData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    claimCode: string;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    machineModel: string;
    /**
     * 
     * @type {StrengthMachineLine}
     * @memberof MachineClaimData
     */
    line: StrengthMachineLine;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    firmwareVersion: string;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    softwareVersion: string;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    mainBoardSerial: string;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    displayUUID: string;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    leftCylinderSerial: string;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimData
     */
    rightCylinderSerial: string;
    /**
     * 
     * @type {MachineClaimStatus}
     * @memberof MachineClaimData
     */
    status: MachineClaimStatus;
    /**
     * 
     * @type {number}
     * @memberof MachineClaimData
     */
    facilityId: number;
    /**
     * 
     * @type {number}
     * @memberof MachineClaimData
     */
    facilityStrengthMachineId: number;
    /**
     * 
     * @type {Date}
     * @memberof MachineClaimData
     */
    expiresAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MachineClaimData
     */
    claimedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MachineClaimData
     */
    confirmedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MachineClaimData
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MachineClaimData
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the MachineClaimData interface.
 */
export function instanceOfMachineClaimData(value: object): value is MachineClaimData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('claimCode' in value) || value['claimCode'] === undefined) return false;
    if (!('machineModel' in value) || value['machineModel'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('firmwareVersion' in value) || value['firmwareVersion'] === undefined) return false;
    if (!('softwareVersion' in value) || value['softwareVersion'] === undefined) return false;
    if (!('mainBoardSerial' in value) || value['mainBoardSerial'] === undefined) return false;
    if (!('displayUUID' in value) || value['displayUUID'] === undefined) return false;
    if (!('leftCylinderSerial' in value) || value['leftCylinderSerial'] === undefined) return false;
    if (!('rightCylinderSerial' in value) || value['rightCylinderSerial'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('facilityId' in value) || value['facilityId'] === undefined) return false;
    if (!('facilityStrengthMachineId' in value) || value['facilityStrengthMachineId'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('claimedAt' in value) || value['claimedAt'] === undefined) return false;
    if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MachineClaimDataFromJSON(json: any): MachineClaimData {
    return MachineClaimDataFromJSONTyped(json, false);
}

export function MachineClaimDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineClaimData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'claimCode': json['claimCode'],
        'machineModel': json['machineModel'],
        'line': StrengthMachineLineFromJSON(json['line']),
        'firmwareVersion': json['firmwareVersion'],
        'softwareVersion': json['softwareVersion'],
        'mainBoardSerial': json['mainBoardSerial'],
        'displayUUID': json['displayUUID'],
        'leftCylinderSerial': json['leftCylinderSerial'],
        'rightCylinderSerial': json['rightCylinderSerial'],
        'status': MachineClaimStatusFromJSON(json['status']),
        'facilityId': json['facilityId'],
        'facilityStrengthMachineId': json['facilityStrengthMachineId'],
        'expiresAt': (new Date(json['expiresAt'])),
        'claimedAt': (new Date(json['claimedAt'])),
        'confirmedAt': (new Date(json['confirmedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function MachineClaimDataToJSON(value?: MachineClaimData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'claimCode': value['claimCode'],
        'machineModel': value['machineModel'],
        'line': StrengthMachineLineToJSON(value['line']),
        'firmwareVersion': value['firmwareVersion'],
        'softwareVersion': value['softwareVersion'],
        'mainBoardSerial': value['mainBoardSerial'],
        'displayUUID': value['displayUUID'],
        'leftCylinderSerial': value['leftCylinderSerial'],
        'rightCylinderSerial': value['rightCylinderSerial'],
        'status': MachineClaimStatusToJSON(value['status']),
        'facilityId': value['facilityId'],
        'facilityStrengthMachineId': value['facilityStrengthMachineId'],
        'expiresAt': ((value['expiresAt']).toISOString()),
        'claimedAt': ((value['claimedAt']).toISOString()),
        'confirmedAt': ((value['confirmedAt']).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

