/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineClaimStatus } from './MachineClaimStatus';
import {
    MachineClaimStatusFromJSON,
    MachineClaimStatusFromJSONTyped,
    MachineClaimStatusToJSON,
} from './MachineClaimStatus';
import type { MachineClaimSorting } from './MachineClaimSorting';
import {
    MachineClaimSortingFromJSON,
    MachineClaimSortingFromJSONTyped,
    MachineClaimSortingToJSON,
} from './MachineClaimSorting';

/**
 * 
 * @export
 * @interface MachineClaimListMeta
 */
export interface MachineClaimListMeta {
    /**
     * 
     * @type {MachineClaimStatus}
     * @memberof MachineClaimListMeta
     */
    status?: MachineClaimStatus;
    /**
     * 
     * @type {MachineClaimSorting}
     * @memberof MachineClaimListMeta
     */
    sort: MachineClaimSorting;
    /**
     * 
     * @type {number}
     * @memberof MachineClaimListMeta
     */
    facilityId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MachineClaimListMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MachineClaimListMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof MachineClaimListMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof MachineClaimListMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the MachineClaimListMeta interface.
 */
export function instanceOfMachineClaimListMeta(value: object): value is MachineClaimListMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function MachineClaimListMetaFromJSON(json: any): MachineClaimListMeta {
    return MachineClaimListMetaFromJSONTyped(json, false);
}

export function MachineClaimListMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineClaimListMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : MachineClaimStatusFromJSON(json['status']),
        'sort': MachineClaimSortingFromJSON(json['sort']),
        'facilityId': json['facilityId'] == null ? undefined : json['facilityId'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function MachineClaimListMetaToJSON(value?: MachineClaimListMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': MachineClaimStatusToJSON(value['status']),
        'sort': MachineClaimSortingToJSON(value['sort']),
        'facilityId': value['facilityId'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

