/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MachineClaimData } from './MachineClaimData';
import {
    MachineClaimDataFromJSON,
    MachineClaimDataFromJSONTyped,
    MachineClaimDataToJSON,
} from './MachineClaimData';

/**
 * 
 * @export
 * @interface MachineClaimClaimResponse
 */
export interface MachineClaimClaimResponse {
    /**
     * 
     * @type {MachineClaimData}
     * @memberof MachineClaimClaimResponse
     */
    machineClaim: MachineClaimData;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimClaimResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof MachineClaimClaimResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the MachineClaimClaimResponse interface.
 */
export function instanceOfMachineClaimClaimResponse(value: object): value is MachineClaimClaimResponse {
    if (!('machineClaim' in value) || value['machineClaim'] === undefined) return false;
    return true;
}

export function MachineClaimClaimResponseFromJSON(json: any): MachineClaimClaimResponse {
    return MachineClaimClaimResponseFromJSONTyped(json, false);
}

export function MachineClaimClaimResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineClaimClaimResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'machineClaim': MachineClaimDataFromJSON(json['machineClaim']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function MachineClaimClaimResponseToJSON(value?: MachineClaimClaimResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'machineClaim': MachineClaimDataToJSON(value['machineClaim']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

