/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const MachineClaimSorting = {
    id: 'id',
    createdAt: 'createdAt'
} as const;
export type MachineClaimSorting =
        | 'id' 
        | 'createdAt' 
;


export function instanceOfMachineClaimSorting(value: unknown): boolean {
    return (Object.values(MachineClaimSorting) as unknown[]).includes(value);
}

export function MachineClaimSortingFromJSON(json: unknown): MachineClaimSorting {
    return MachineClaimSortingFromJSONTyped(json, false);
}

export function MachineClaimSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): MachineClaimSorting {
    return json as MachineClaimSorting;
}

export function MachineClaimSortingToJSON(value?: MachineClaimSorting | null): MachineClaimSorting | null | undefined {
    return value;
}

