/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MSeriesAppSessionListResponseMeta
 */
export interface MSeriesAppSessionListResponseMeta {
    /**
     * 
     * @type {Date}
     * @memberof MSeriesAppSessionListResponseMeta
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MSeriesAppSessionListResponseMeta
     */
    to?: Date;
    /**
     * 
     * @type {string}
     * @memberof MSeriesAppSessionListResponseMeta
     */
    sort?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MSeriesAppSessionListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MSeriesAppSessionListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof MSeriesAppSessionListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof MSeriesAppSessionListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the MSeriesAppSessionListResponseMeta interface.
 */
export function instanceOfMSeriesAppSessionListResponseMeta(value: object): value is MSeriesAppSessionListResponseMeta {
    return true;
}

export function MSeriesAppSessionListResponseMetaFromJSON(json: any): MSeriesAppSessionListResponseMeta {
    return MSeriesAppSessionListResponseMetaFromJSONTyped(json, false);
}

export function MSeriesAppSessionListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MSeriesAppSessionListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'sort': json['sort'] == null ? undefined : json['sort'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function MSeriesAppSessionListResponseMetaToJSON(value?: MSeriesAppSessionListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
        'sort': value['sort'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

