/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardioMachineData } from './CardioMachineData';
import {
    CardioMachineDataFromJSON,
    CardioMachineDataFromJSONTyped,
    CardioMachineDataToJSON,
} from './CardioMachineData';
import type { WeightMeasurementData } from './WeightMeasurementData';
import {
    WeightMeasurementDataFromJSON,
    WeightMeasurementDataFromJSONTyped,
    WeightMeasurementDataToJSON,
} from './WeightMeasurementData';
import type { HeartRateDataSetSessionData } from './HeartRateDataSetSessionData';
import {
    HeartRateDataSetSessionDataFromJSON,
    HeartRateDataSetSessionDataFromJSONTyped,
    HeartRateDataSetSessionDataToJSON,
} from './HeartRateDataSetSessionData';
import type { MSeriesFtpMeasurementData } from './MSeriesFtpMeasurementData';
import {
    MSeriesFtpMeasurementDataFromJSON,
    MSeriesFtpMeasurementDataFromJSONTyped,
    MSeriesFtpMeasurementDataToJSON,
} from './MSeriesFtpMeasurementData';
import type { MSeriesDataSetSegmentData } from './MSeriesDataSetSegmentData';
import {
    MSeriesDataSetSegmentDataFromJSON,
    MSeriesDataSetSegmentDataFromJSONTyped,
    MSeriesDataSetSegmentDataToJSON,
} from './MSeriesDataSetSegmentData';
import type { HeightMeasurementData } from './HeightMeasurementData';
import {
    HeightMeasurementDataFromJSON,
    HeightMeasurementDataFromJSONTyped,
    HeightMeasurementDataToJSON,
} from './HeightMeasurementData';
import type { MSeriesDataSetData } from './MSeriesDataSetData';
import {
    MSeriesDataSetDataFromJSON,
    MSeriesDataSetDataFromJSONTyped,
    MSeriesDataSetDataToJSON,
} from './MSeriesDataSetData';
import type { Zones } from './Zones';
import {
    ZonesFromJSON,
    ZonesFromJSONTyped,
    ZonesToJSON,
} from './Zones';

/**
 * 
 * @export
 * @interface MSeriesAppSessionData
 */
export interface MSeriesAppSessionData {
    /**
     * 
     * @type {number}
     * @memberof MSeriesAppSessionData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MSeriesAppSessionData
     */
    source?: string;
    /**
     * 
     * @type {Date}
     * @memberof MSeriesAppSessionData
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MSeriesAppSessionData
     */
    endedAt?: Date;
    /**
     * 
     * @type {CardioMachineData}
     * @memberof MSeriesAppSessionData
     */
    cardioMachine?: CardioMachineData;
    /**
     * 
     * @type {number}
     * @memberof MSeriesAppSessionData
     */
    ordinalId?: number;
    /**
     * 
     * @type {MSeriesDataSetData}
     * @memberof MSeriesAppSessionData
     */
    mSeriesDataSet?: MSeriesDataSetData;
    /**
     * 
     * @type {string}
     * @memberof MSeriesAppSessionData
     */
    machineType?: string;
    /**
     * 
     * @type {Array<MSeriesDataSetSegmentData>}
     * @memberof MSeriesAppSessionData
     */
    mSeriesDataSetSegment?: Array<MSeriesDataSetSegmentData>;
    /**
     * 
     * @type {MSeriesFtpMeasurementData}
     * @memberof MSeriesAppSessionData
     */
    mSeriesFtpMeasurement?: MSeriesFtpMeasurementData;
    /**
     * 
     * @type {Zones}
     * @memberof MSeriesAppSessionData
     */
    durationInZones?: Zones;
    /**
     * 
     * @type {HeartRateDataSetSessionData}
     * @memberof MSeriesAppSessionData
     */
    heartRateDataSet?: HeartRateDataSetSessionData;
    /**
     * 
     * @type {WeightMeasurementData}
     * @memberof MSeriesAppSessionData
     */
    weightMeasurement?: WeightMeasurementData;
    /**
     * 
     * @type {HeightMeasurementData}
     * @memberof MSeriesAppSessionData
     */
    heightMeasurement?: HeightMeasurementData;
}

/**
 * Check if a given object implements the MSeriesAppSessionData interface.
 */
export function instanceOfMSeriesAppSessionData(value: object): value is MSeriesAppSessionData {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MSeriesAppSessionDataFromJSON(json: any): MSeriesAppSessionData {
    return MSeriesAppSessionDataFromJSONTyped(json, false);
}

export function MSeriesAppSessionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MSeriesAppSessionData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'source': json['source'] == null ? undefined : json['source'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'cardioMachine': json['cardioMachine'] == null ? undefined : CardioMachineDataFromJSON(json['cardioMachine']),
        'ordinalId': json['ordinalId'] == null ? undefined : json['ordinalId'],
        'mSeriesDataSet': json['mSeriesDataSet'] == null ? undefined : MSeriesDataSetDataFromJSON(json['mSeriesDataSet']),
        'machineType': json['machineType'] == null ? undefined : json['machineType'],
        'mSeriesDataSetSegment': json['mSeriesDataSetSegment'] == null ? undefined : ((json['mSeriesDataSetSegment'] as Array<any>).map(MSeriesDataSetSegmentDataFromJSON)),
        'mSeriesFtpMeasurement': json['mSeriesFtpMeasurement'] == null ? undefined : MSeriesFtpMeasurementDataFromJSON(json['mSeriesFtpMeasurement']),
        'durationInZones': json['durationInZones'] == null ? undefined : ZonesFromJSON(json['durationInZones']),
        'heartRateDataSet': json['heartRateDataSet'] == null ? undefined : HeartRateDataSetSessionDataFromJSON(json['heartRateDataSet']),
        'weightMeasurement': json['weightMeasurement'] == null ? undefined : WeightMeasurementDataFromJSON(json['weightMeasurement']),
        'heightMeasurement': json['heightMeasurement'] == null ? undefined : HeightMeasurementDataFromJSON(json['heightMeasurement']),
    };
}

export function MSeriesAppSessionDataToJSON(value?: MSeriesAppSessionData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'source': value['source'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt']).toISOString()),
        'cardioMachine': CardioMachineDataToJSON(value['cardioMachine']),
        'ordinalId': value['ordinalId'],
        'mSeriesDataSet': MSeriesDataSetDataToJSON(value['mSeriesDataSet']),
        'machineType': value['machineType'],
        'mSeriesDataSetSegment': value['mSeriesDataSetSegment'] == null ? undefined : ((value['mSeriesDataSetSegment'] as Array<any>).map(MSeriesDataSetSegmentDataToJSON)),
        'mSeriesFtpMeasurement': MSeriesFtpMeasurementDataToJSON(value['mSeriesFtpMeasurement']),
        'durationInZones': ZonesToJSON(value['durationInZones']),
        'heartRateDataSet': HeartRateDataSetSessionDataToJSON(value['heartRateDataSet']),
        'weightMeasurement': WeightMeasurementDataToJSON(value['weightMeasurement']),
        'heightMeasurement': HeightMeasurementDataToJSON(value['heightMeasurement']),
    };
}

