/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MSeriesDataSetListResponseMeta } from './MSeriesDataSetListResponseMeta';
import {
    MSeriesDataSetListResponseMetaFromJSON,
    MSeriesDataSetListResponseMetaFromJSONTyped,
    MSeriesDataSetListResponseMetaToJSON,
} from './MSeriesDataSetListResponseMeta';
import type { MSeriesDataSetData } from './MSeriesDataSetData';
import {
    MSeriesDataSetDataFromJSON,
    MSeriesDataSetDataFromJSONTyped,
    MSeriesDataSetDataToJSON,
} from './MSeriesDataSetData';

/**
 * 
 * @export
 * @interface MSeriesDataSetListResponse
 */
export interface MSeriesDataSetListResponse {
    /**
     * 
     * @type {Array<MSeriesDataSetData>}
     * @memberof MSeriesDataSetListResponse
     */
    mSeriesDataSets: Array<MSeriesDataSetData>;
    /**
     * 
     * @type {MSeriesDataSetListResponseMeta}
     * @memberof MSeriesDataSetListResponse
     */
    mSeriesDataSetsMeta: MSeriesDataSetListResponseMeta;
    /**
     * 
     * @type {string}
     * @memberof MSeriesDataSetListResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof MSeriesDataSetListResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the MSeriesDataSetListResponse interface.
 */
export function instanceOfMSeriesDataSetListResponse(value: object): value is MSeriesDataSetListResponse {
    if (!('mSeriesDataSets' in value) || value['mSeriesDataSets'] === undefined) return false;
    if (!('mSeriesDataSetsMeta' in value) || value['mSeriesDataSetsMeta'] === undefined) return false;
    return true;
}

export function MSeriesDataSetListResponseFromJSON(json: any): MSeriesDataSetListResponse {
    return MSeriesDataSetListResponseFromJSONTyped(json, false);
}

export function MSeriesDataSetListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MSeriesDataSetListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'mSeriesDataSets': ((json['mSeriesDataSets'] as Array<any>).map(MSeriesDataSetDataFromJSON)),
        'mSeriesDataSetsMeta': MSeriesDataSetListResponseMetaFromJSON(json['mSeriesDataSetsMeta']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function MSeriesDataSetListResponseToJSON(value?: MSeriesDataSetListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mSeriesDataSets': ((value['mSeriesDataSets'] as Array<any>).map(MSeriesDataSetDataToJSON)),
        'mSeriesDataSetsMeta': MSeriesDataSetListResponseMetaToJSON(value['mSeriesDataSetsMeta']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

