/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const MSeriesFtpMeasurementSorting = {
    id: 'id',
    takenAt: 'takenAt',
    source: 'source'
} as const;
export type MSeriesFtpMeasurementSorting =
        | 'id' 
        | 'takenAt' 
        | 'source' 
;


export function instanceOfMSeriesFtpMeasurementSorting(value: unknown): boolean {
    return (Object.values(MSeriesFtpMeasurementSorting) as unknown[]).includes(value);
}

export function MSeriesFtpMeasurementSortingFromJSON(json: unknown): MSeriesFtpMeasurementSorting {
    return MSeriesFtpMeasurementSortingFromJSONTyped(json, false);
}

export function MSeriesFtpMeasurementSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): MSeriesFtpMeasurementSorting {
    return json as MSeriesFtpMeasurementSorting;
}

export function MSeriesFtpMeasurementSortingToJSON(value?: MSeriesFtpMeasurementSorting | null): MSeriesFtpMeasurementSorting | null | undefined {
    return value;
}

