/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const MuscleArea = {
    lowerBody: 'lowerBody',
    upperBody: 'upperBody',
    core: 'core'
} as const;
export type MuscleArea =
        | 'lowerBody' 
        | 'upperBody' 
        | 'core' 
;


export function instanceOfMuscleArea(value: unknown): boolean {
    return (Object.values(MuscleArea) as unknown[]).includes(value);
}

export function MuscleAreaFromJSON(json: unknown): MuscleArea {
    return MuscleAreaFromJSONTyped(json, false);
}

export function MuscleAreaFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): MuscleArea {
    return json as MuscleArea;
}

export function MuscleAreaToJSON(value?: MuscleArea | null): MuscleArea | null | undefined {
    return value;
}

