/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const MuscleTargetLevel = {
    primary: 'primary',
    secondary: 'secondary',
    tertiary: 'tertiary'
} as const;
export type MuscleTargetLevel =
        | 'primary' 
        | 'secondary' 
        | 'tertiary' 
;


export function instanceOfMuscleTargetLevel(value: unknown): boolean {
    return (Object.values(MuscleTargetLevel) as unknown[]).includes(value);
}

export function MuscleTargetLevelFromJSON(json: unknown): MuscleTargetLevel {
    return MuscleTargetLevelFromJSONTyped(json, false);
}

export function MuscleTargetLevelFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): MuscleTargetLevel {
    return json as MuscleTargetLevel;
}

export function MuscleTargetLevelToJSON(value?: MuscleTargetLevel | null): MuscleTargetLevel | null | undefined {
    return value;
}

