/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OAuthServiceData } from './OAuthServiceData';
import {
    OAuthServiceDataFromJSON,
    OAuthServiceDataFromJSONTyped,
    OAuthServiceDataToJSON,
} from './OAuthServiceData';

/**
 * 
 * @export
 * @interface OAuthServiceResponse
 */
export interface OAuthServiceResponse {
    /**
     * 
     * @type {OAuthServiceData}
     * @memberof OAuthServiceResponse
     */
    oauthService: OAuthServiceData;
    /**
     * 
     * @type {string}
     * @memberof OAuthServiceResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthServiceResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the OAuthServiceResponse interface.
 */
export function instanceOfOAuthServiceResponse(value: object): value is OAuthServiceResponse {
    if (!('oauthService' in value) || value['oauthService'] === undefined) return false;
    return true;
}

export function OAuthServiceResponseFromJSON(json: any): OAuthServiceResponse {
    return OAuthServiceResponseFromJSONTyped(json, false);
}

export function OAuthServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'oauthService': OAuthServiceDataFromJSON(json['oauthService']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function OAuthServiceResponseToJSON(value?: OAuthServiceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'oauthService': OAuthServiceDataToJSON(value['oauthService']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

