/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OAuthServiceSorting } from './OAuthServiceSorting';
import {
    OAuthServiceSortingFromJSON,
    OAuthServiceSortingFromJSONTyped,
    OAuthServiceSortingToJSON,
} from './OAuthServiceSorting';

/**
 * 
 * @export
 * @interface OAuthServiceListResponseMeta
 */
export interface OAuthServiceListResponseMeta {
    /**
     * 
     * @type {OAuthServiceSorting}
     * @memberof OAuthServiceListResponseMeta
     */
    sort: OAuthServiceSorting;
    /**
     * 
     * @type {string}
     * @memberof OAuthServiceListResponseMeta
     */
    service?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OAuthServiceListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OAuthServiceListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof OAuthServiceListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof OAuthServiceListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the OAuthServiceListResponseMeta interface.
 */
export function instanceOfOAuthServiceListResponseMeta(value: object): value is OAuthServiceListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function OAuthServiceListResponseMetaFromJSON(json: any): OAuthServiceListResponseMeta {
    return OAuthServiceListResponseMetaFromJSONTyped(json, false);
}

export function OAuthServiceListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthServiceListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'sort': OAuthServiceSortingFromJSON(json['sort']),
        'service': json['service'] == null ? undefined : json['service'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function OAuthServiceListResponseMetaToJSON(value?: OAuthServiceListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': OAuthServiceSortingToJSON(value['sort']),
        'service': value['service'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

