/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResistancePrecision = {
    Int: 'int',
    Dec: 'dec'
} as const;
export type ResistancePrecision =
        | 'int' 
        | 'dec' 
;


export function ResistancePrecisionFromJSON(json: any): ResistancePrecision {
    return ResistancePrecisionFromJSONTyped(json, false);
}

export function ResistancePrecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResistancePrecision {
    return json as ResistancePrecision;
}

export function ResistancePrecisionToJSON(value?: ResistancePrecision | null): any {
    return value as any;
}

