/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const ResistancePrecision = {
    int: 'int',
    dec: 'dec'
} as const;
export type ResistancePrecision =
        | 'int' 
        | 'dec' 
;


export function instanceOfResistancePrecision(value: unknown): boolean {
    return (Object.values(ResistancePrecision) as unknown[]).includes(value);
}

export function ResistancePrecisionFromJSON(json: unknown): ResistancePrecision {
    return ResistancePrecisionFromJSONTyped(json, false);
}

export function ResistancePrecisionFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): ResistancePrecision {
    return json as ResistancePrecision;
}

export function ResistancePrecisionToJSON(value?: ResistancePrecision | null): ResistancePrecision | null | undefined {
    return value;
}

