/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaintenanceStatus } from './MaintenanceStatus';
import {
    MaintenanceStatusFromJSON,
    MaintenanceStatusFromJSONTyped,
    MaintenanceStatusToJSON,
} from './MaintenanceStatus';

/**
 * 
 * @export
 * @interface ServiceStatusResponse
 */
export interface ServiceStatusResponse {
    /**
     * 
     * @type {MaintenanceStatus}
     * @memberof ServiceStatusResponse
     */
    maintenance: MaintenanceStatus;
}

/**
 * Check if a given object implements the ServiceStatusResponse interface.
 */
export function instanceOfServiceStatusResponse(value: object): value is ServiceStatusResponse {
    if (!('maintenance' in value) || value['maintenance'] === undefined) return false;
    return true;
}

export function ServiceStatusResponseFromJSON(json: any): ServiceStatusResponse {
    return ServiceStatusResponseFromJSONTyped(json, false);
}

export function ServiceStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'maintenance': MaintenanceStatusFromJSON(json['maintenance']),
    };
}

export function ServiceStatusResponseToJSON(value?: ServiceStatusResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'maintenance': MaintenanceStatusToJSON(value['maintenance']),
    };
}

