/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionPlanSetTemplateData } from './SessionPlanSetTemplateData';
import {
    SessionPlanSetTemplateDataFromJSON,
    SessionPlanSetTemplateDataFromJSONTyped,
    SessionPlanSetTemplateDataToJSON,
} from './SessionPlanSetTemplateData';
import type { UserData } from './UserData';
import {
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './UserData';

/**
 * 
 * @export
 * @interface SessionPlanSequenceTemplateData
 */
export interface SessionPlanSequenceTemplateData {
    /**
     * 
     * @type {number}
     * @memberof SessionPlanSequenceTemplateData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SessionPlanSequenceTemplateData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SessionPlanSequenceTemplateData
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof SessionPlanSequenceTemplateData
     */
    notes: string;
    /**
     * 
     * @type {boolean}
     * @memberof SessionPlanSequenceTemplateData
     */
    searchable: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SessionPlanSequenceTemplateData
     */
    _public: boolean;
    /**
     * 
     * @type {UserData}
     * @memberof SessionPlanSequenceTemplateData
     */
    user?: UserData;
    /**
     * 
     * @type {Array<SessionPlanSetTemplateData>}
     * @memberof SessionPlanSequenceTemplateData
     */
    sessionPlanSetTemplates?: Array<SessionPlanSetTemplateData>;
}

/**
 * Check if a given object implements the SessionPlanSequenceTemplateData interface.
 */
export function instanceOfSessionPlanSequenceTemplateData(value: object): value is SessionPlanSequenceTemplateData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('searchable' in value) || value['searchable'] === undefined) return false;
    if (!('_public' in value) || value['_public'] === undefined) return false;
    return true;
}

export function SessionPlanSequenceTemplateDataFromJSON(json: any): SessionPlanSequenceTemplateData {
    return SessionPlanSequenceTemplateDataFromJSONTyped(json, false);
}

export function SessionPlanSequenceTemplateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPlanSequenceTemplateData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'notes': json['notes'],
        'searchable': json['searchable'],
        '_public': json['public'],
        'user': json['user'] == null ? undefined : UserDataFromJSON(json['user']),
        'sessionPlanSetTemplates': json['sessionPlanSetTemplates'] == null ? undefined : ((json['sessionPlanSetTemplates'] as Array<any>).map(SessionPlanSetTemplateDataFromJSON)),
    };
}

export function SessionPlanSequenceTemplateDataToJSON(value?: SessionPlanSequenceTemplateData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'notes': value['notes'],
        'searchable': value['searchable'],
        'public': value['_public'],
        'user': UserDataToJSON(value['user']),
        'sessionPlanSetTemplates': value['sessionPlanSetTemplates'] == null ? undefined : ((value['sessionPlanSetTemplates'] as Array<any>).map(SessionPlanSetTemplateDataToJSON)),
    };
}

