/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionPlanSequenceTemplateMeta
 */
export interface SessionPlanSequenceTemplateMeta {
    /**
     * 
     * @type {string}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    searchable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    _public?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    sort?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof SessionPlanSequenceTemplateMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the SessionPlanSequenceTemplateMeta interface.
 */
export function instanceOfSessionPlanSequenceTemplateMeta(value: object): value is SessionPlanSequenceTemplateMeta {
    return true;
}

export function SessionPlanSequenceTemplateMetaFromJSON(json: any): SessionPlanSequenceTemplateMeta {
    return SessionPlanSequenceTemplateMetaFromJSONTyped(json, false);
}

export function SessionPlanSequenceTemplateMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPlanSequenceTemplateMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'searchable': json['searchable'] == null ? undefined : json['searchable'],
        '_public': json['public'] == null ? undefined : json['public'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function SessionPlanSequenceTemplateMetaToJSON(value?: SessionPlanSequenceTemplateMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'searchable': value['searchable'],
        'public': value['_public'],
        'sort': value['sort'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

