/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionPlanStretchSetData
 */
export interface SessionPlanStretchSetData {
    /**
     * 
     * @type {string}
     * @memberof SessionPlanStretchSetData
     */
    name: string;
}

/**
 * Check if a given object implements the SessionPlanStretchSetData interface.
 */
export function instanceOfSessionPlanStretchSetData(value: object): value is SessionPlanStretchSetData {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SessionPlanStretchSetDataFromJSON(json: any): SessionPlanStretchSetData {
    return SessionPlanStretchSetDataFromJSONTyped(json, false);
}

export function SessionPlanStretchSetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPlanStretchSetData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SessionPlanStretchSetDataToJSON(value?: SessionPlanStretchSetData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

