/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionData } from './SessionData';
import {
    SessionDataFromJSON,
    SessionDataFromJSONTyped,
    SessionDataToJSON,
} from './SessionData';

/**
 * 
 * @export
 * @interface SessionStartResponse
 */
export interface SessionStartResponse {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SessionStartResponse
     */
    echipData: { [key: string]: any; };
    /**
     * 
     * @type {SessionData}
     * @memberof SessionStartResponse
     */
    session?: SessionData;
    /**
     * 
     * @type {string}
     * @memberof SessionStartResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionStartResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the SessionStartResponse interface.
 */
export function instanceOfSessionStartResponse(value: object): value is SessionStartResponse {
    if (!('echipData' in value) || value['echipData'] === undefined) return false;
    return true;
}

export function SessionStartResponseFromJSON(json: any): SessionStartResponse {
    return SessionStartResponseFromJSONTyped(json, false);
}

export function SessionStartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionStartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'echipData': json['echipData'],
        'session': json['session'] == null ? undefined : SessionDataFromJSON(json['session']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function SessionStartResponseToJSON(value?: SessionStartResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'echipData': value['echipData'],
        'session': SessionDataToJSON(value['session']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

