/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SessionPlanActivitySetData } from './SessionPlanActivitySetData';
import {
    SessionPlanActivitySetDataFromJSON,
    SessionPlanActivitySetDataFromJSONTyped,
    SessionPlanActivitySetDataToJSON,
} from './SessionPlanActivitySetData';
import type { SessionPlanCardioSetData } from './SessionPlanCardioSetData';
import {
    SessionPlanCardioSetDataFromJSON,
    SessionPlanCardioSetDataFromJSONTyped,
    SessionPlanCardioSetDataToJSON,
} from './SessionPlanCardioSetData';
import type { SessionPlanSetType } from './SessionPlanSetType';
import {
    SessionPlanSetTypeFromJSON,
    SessionPlanSetTypeFromJSONTyped,
    SessionPlanSetTypeToJSON,
} from './SessionPlanSetType';
import type { SessionPlanStrengthSetData } from './SessionPlanStrengthSetData';
import {
    SessionPlanStrengthSetDataFromJSON,
    SessionPlanStrengthSetDataFromJSONTyped,
    SessionPlanStrengthSetDataToJSON,
} from './SessionPlanStrengthSetData';
import type { SessionPlanStretchSetData } from './SessionPlanStretchSetData';
import {
    SessionPlanStretchSetDataFromJSON,
    SessionPlanStretchSetDataFromJSONTyped,
    SessionPlanStretchSetDataToJSON,
} from './SessionPlanStretchSetData';

/**
 * 
 * @export
 * @interface SessionPlanSetData
 */
export interface SessionPlanSetData {
    /**
     * 
     * @type {number}
     * @memberof SessionPlanSetData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SessionPlanSetData
     */
    notes?: string;
    /**
     * 
     * @type {SessionPlanSetType}
     * @memberof SessionPlanSetData
     */
    type?: SessionPlanSetType;
    /**
     * 
     * @type {SessionPlanCardioSetData}
     * @memberof SessionPlanSetData
     */
    sessionPlanCardioSet?: SessionPlanCardioSetData;
    /**
     * 
     * @type {SessionPlanStrengthSetData}
     * @memberof SessionPlanSetData
     */
    sessionPlanStrengthSet?: SessionPlanStrengthSetData;
    /**
     * 
     * @type {SessionPlanStretchSetData}
     * @memberof SessionPlanSetData
     */
    sessionPlanStretchSet?: SessionPlanStretchSetData;
    /**
     * 
     * @type {SessionPlanActivitySetData}
     * @memberof SessionPlanSetData
     */
    sessionPlanAcvivitySet?: SessionPlanActivitySetData;
}

/**
 * Check if a given object implements the SessionPlanSetData interface.
 */
export function instanceOfSessionPlanSetData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SessionPlanSetDataFromJSON(json: any): SessionPlanSetData {
    return SessionPlanSetDataFromJSONTyped(json, false);
}

export function SessionPlanSetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPlanSetData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'type': !exists(json, 'type') ? undefined : SessionPlanSetTypeFromJSON(json['type']),
        'sessionPlanCardioSet': !exists(json, 'sessionPlanCardioSet') ? undefined : SessionPlanCardioSetDataFromJSON(json['sessionPlanCardioSet']),
        'sessionPlanStrengthSet': !exists(json, 'sessionPlanStrengthSet') ? undefined : SessionPlanStrengthSetDataFromJSON(json['sessionPlanStrengthSet']),
        'sessionPlanStretchSet': !exists(json, 'sessionPlanStretchSet') ? undefined : SessionPlanStretchSetDataFromJSON(json['sessionPlanStretchSet']),
        'sessionPlanAcvivitySet': !exists(json, 'sessionPlanAcvivitySet') ? undefined : SessionPlanActivitySetDataFromJSON(json['sessionPlanAcvivitySet']),
    };
}

export function SessionPlanSetDataToJSON(value?: SessionPlanSetData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'notes': value.notes,
        'type': SessionPlanSetTypeToJSON(value.type),
        'sessionPlanCardioSet': SessionPlanCardioSetDataToJSON(value.sessionPlanCardioSet),
        'sessionPlanStrengthSet': SessionPlanStrengthSetDataToJSON(value.sessionPlanStrengthSet),
        'sessionPlanStretchSet': SessionPlanStretchSetDataToJSON(value.sessionPlanStretchSet),
        'sessionPlanAcvivitySet': SessionPlanActivitySetDataToJSON(value.sessionPlanAcvivitySet),
    };
}

