/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacilityData } from './FacilityData';
import {
    FacilityDataFromJSON,
    FacilityDataFromJSONTyped,
    FacilityDataToJSON,
} from './FacilityData';
import type { SessionPlanSequenceInstanceData } from './SessionPlanSequenceInstanceData';
import {
    SessionPlanSequenceInstanceDataFromJSON,
    SessionPlanSequenceInstanceDataFromJSONTyped,
    SessionPlanSequenceInstanceDataToJSON,
} from './SessionPlanSequenceInstanceData';
import type { WeightMeasurementData } from './WeightMeasurementData';
import {
    WeightMeasurementDataFromJSON,
    WeightMeasurementDataFromJSONTyped,
    WeightMeasurementDataToJSON,
} from './WeightMeasurementData';
import type { UserData } from './UserData';
import {
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './UserData';
import type { HeightMeasurementData } from './HeightMeasurementData';
import {
    HeightMeasurementDataFromJSON,
    HeightMeasurementDataFromJSONTyped,
    HeightMeasurementDataToJSON,
} from './HeightMeasurementData';
import type { MSeriesDataSetData } from './MSeriesDataSetData';
import {
    MSeriesDataSetDataFromJSON,
    MSeriesDataSetDataFromJSONTyped,
    MSeriesDataSetDataToJSON,
} from './MSeriesDataSetData';
import type { StrengthMachineDataSetData } from './StrengthMachineDataSetData';
import {
    StrengthMachineDataSetDataFromJSON,
    StrengthMachineDataSetDataFromJSONTyped,
    StrengthMachineDataSetDataToJSON,
} from './StrengthMachineDataSetData';
import type { HeartRateDataSetData } from './HeartRateDataSetData';
import {
    HeartRateDataSetDataFromJSON,
    HeartRateDataSetDataFromJSONTyped,
    HeartRateDataSetDataToJSON,
} from './HeartRateDataSetData';

/**
 * 
 * @export
 * @interface SessionData
 */
export interface SessionData {
    /**
     * 
     * @type {number}
     * @memberof SessionData
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof SessionData
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof SessionData
     */
    echipId?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionData
     */
    hash: string;
    /**
     * 
     * @type {Date}
     * @memberof SessionData
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SessionData
     */
    endedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SessionData
     */
    hasMSeriesDataSets: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SessionData
     */
    hasStrengthMachineDataSets: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SessionData
     */
    hasHeartRateDataSets: boolean;
    /**
     * 
     * @type {UserData}
     * @memberof SessionData
     */
    user?: UserData;
    /**
     * 
     * @type {FacilityData}
     * @memberof SessionData
     */
    facility?: FacilityData;
    /**
     * 
     * @type {SessionPlanSequenceInstanceData}
     * @memberof SessionData
     */
    sessionPlanSequenceInstance?: SessionPlanSequenceInstanceData;
    /**
     * 
     * @type {Array<HeartRateDataSetData>}
     * @memberof SessionData
     */
    heartRateDataSets?: Array<HeartRateDataSetData>;
    /**
     * 
     * @type {Array<MSeriesDataSetData>}
     * @memberof SessionData
     */
    mSeriesDataSets?: Array<MSeriesDataSetData>;
    /**
     * 
     * @type {Array<StrengthMachineDataSetData>}
     * @memberof SessionData
     */
    strengthMachineDataSets?: Array<StrengthMachineDataSetData>;
    /**
     * 
     * @type {HeightMeasurementData}
     * @memberof SessionData
     */
    heightMeasurement?: HeightMeasurementData;
    /**
     * 
     * @type {WeightMeasurementData}
     * @memberof SessionData
     */
    weightMeasurement?: WeightMeasurementData;
}

/**
 * Check if a given object implements the SessionData interface.
 */
export function instanceOfSessionData(value: object): value is SessionData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('hasMSeriesDataSets' in value) || value['hasMSeriesDataSets'] === undefined) return false;
    if (!('hasStrengthMachineDataSets' in value) || value['hasStrengthMachineDataSets'] === undefined) return false;
    if (!('hasHeartRateDataSets' in value) || value['hasHeartRateDataSets'] === undefined) return false;
    return true;
}

export function SessionDataFromJSON(json: any): SessionData {
    return SessionDataFromJSONTyped(json, false);
}

export function SessionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'echipId': json['echipId'] == null ? undefined : json['echipId'],
        'hash': json['hash'],
        'startedAt': (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'hasMSeriesDataSets': json['hasMSeriesDataSets'],
        'hasStrengthMachineDataSets': json['hasStrengthMachineDataSets'],
        'hasHeartRateDataSets': json['hasHeartRateDataSets'],
        'user': json['user'] == null ? undefined : UserDataFromJSON(json['user']),
        'facility': json['facility'] == null ? undefined : FacilityDataFromJSON(json['facility']),
        'sessionPlanSequenceInstance': json['sessionPlanSequenceInstance'] == null ? undefined : SessionPlanSequenceInstanceDataFromJSON(json['sessionPlanSequenceInstance']),
        'heartRateDataSets': json['heartRateDataSets'] == null ? undefined : ((json['heartRateDataSets'] as Array<any>).map(HeartRateDataSetDataFromJSON)),
        'mSeriesDataSets': json['mSeriesDataSets'] == null ? undefined : ((json['mSeriesDataSets'] as Array<any>).map(MSeriesDataSetDataFromJSON)),
        'strengthMachineDataSets': json['strengthMachineDataSets'] == null ? undefined : ((json['strengthMachineDataSets'] as Array<any>).map(StrengthMachineDataSetDataFromJSON)),
        'heightMeasurement': json['heightMeasurement'] == null ? undefined : HeightMeasurementDataFromJSON(json['heightMeasurement']),
        'weightMeasurement': json['weightMeasurement'] == null ? undefined : WeightMeasurementDataFromJSON(json['weightMeasurement']),
    };
}

export function SessionDataToJSON(value?: SessionData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'echipId': value['echipId'],
        'hash': value['hash'],
        'startedAt': ((value['startedAt']).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt']).toISOString()),
        'hasMSeriesDataSets': value['hasMSeriesDataSets'],
        'hasStrengthMachineDataSets': value['hasStrengthMachineDataSets'],
        'hasHeartRateDataSets': value['hasHeartRateDataSets'],
        'user': UserDataToJSON(value['user']),
        'facility': FacilityDataToJSON(value['facility']),
        'sessionPlanSequenceInstance': SessionPlanSequenceInstanceDataToJSON(value['sessionPlanSequenceInstance']),
        'heartRateDataSets': value['heartRateDataSets'] == null ? undefined : ((value['heartRateDataSets'] as Array<any>).map(HeartRateDataSetDataToJSON)),
        'mSeriesDataSets': value['mSeriesDataSets'] == null ? undefined : ((value['mSeriesDataSets'] as Array<any>).map(MSeriesDataSetDataToJSON)),
        'strengthMachineDataSets': value['strengthMachineDataSets'] == null ? undefined : ((value['strengthMachineDataSets'] as Array<any>).map(StrengthMachineDataSetDataToJSON)),
        'heightMeasurement': HeightMeasurementDataToJSON(value['heightMeasurement']),
        'weightMeasurement': WeightMeasurementDataToJSON(value['weightMeasurement']),
    };
}

