/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const SessionSorting = {
    id: 'id',
    startedAt: 'startedAt',
    endedAt: 'endedAt',
    name: 'name',
    open: 'open'
} as const;
export type SessionSorting =
        | 'id' 
        | 'startedAt' 
        | 'endedAt' 
        | 'name' 
        | 'open' 
;


export function instanceOfSessionSorting(value: unknown): boolean {
    return (Object.values(SessionSorting) as unknown[]).includes(value);
}

export function SessionSortingFromJSON(json: unknown): SessionSorting {
    return SessionSortingFromJSONTyped(json, false);
}

export function SessionSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): SessionSorting {
    return json as SessionSorting;
}

export function SessionSortingToJSON(value?: SessionSorting | null): SessionSorting | null | undefined {
    return value;
}

