/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionPlanSequenceData } from './SessionPlanSequenceData';
import {
    SessionPlanSequenceDataFromJSON,
    SessionPlanSequenceDataFromJSONTyped,
    SessionPlanSequenceDataToJSON,
} from './SessionPlanSequenceData';

/**
 * 
 * @export
 * @interface SessionPlanSequenceAssignmentData
 */
export interface SessionPlanSequenceAssignmentData {
    /**
     * 
     * @type {number}
     * @memberof SessionPlanSequenceAssignmentData
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof SessionPlanSequenceAssignmentData
     */
    scheduleIndex: number;
    /**
     * 
     * @type {SessionPlanSequenceData}
     * @memberof SessionPlanSequenceAssignmentData
     */
    sessionPlanSequence?: SessionPlanSequenceData;
}

/**
 * Check if a given object implements the SessionPlanSequenceAssignmentData interface.
 */
export function instanceOfSessionPlanSequenceAssignmentData(value: object): value is SessionPlanSequenceAssignmentData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scheduleIndex' in value) || value['scheduleIndex'] === undefined) return false;
    return true;
}

export function SessionPlanSequenceAssignmentDataFromJSON(json: any): SessionPlanSequenceAssignmentData {
    return SessionPlanSequenceAssignmentDataFromJSONTyped(json, false);
}

export function SessionPlanSequenceAssignmentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPlanSequenceAssignmentData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scheduleIndex': json['scheduleIndex'],
        'sessionPlanSequence': json['sessionPlanSequence'] == null ? undefined : SessionPlanSequenceDataFromJSON(json['sessionPlanSequence']),
    };
}

export function SessionPlanSequenceAssignmentDataToJSON(value?: SessionPlanSequenceAssignmentData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'scheduleIndex': value['scheduleIndex'],
        'sessionPlanSequence': SessionPlanSequenceDataToJSON(value['sessionPlanSequence']),
    };
}

