/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForceUnit } from './ForceUnit';
import {
    ForceUnitFromJSON,
    ForceUnitFromJSONTyped,
    ForceUnitToJSON,
} from './ForceUnit';
import type { StrengthMachineData } from './StrengthMachineData';
import {
    StrengthMachineDataFromJSON,
    StrengthMachineDataFromJSONTyped,
    StrengthMachineDataToJSON,
} from './StrengthMachineData';
import type { StrengthExerciseData } from './StrengthExerciseData';
import {
    StrengthExerciseDataFromJSON,
    StrengthExerciseDataFromJSONTyped,
    StrengthExerciseDataToJSON,
} from './StrengthExerciseData';

/**
 * 
 * @export
 * @interface SessionPlanStrengthSetData
 */
export interface SessionPlanStrengthSetData {
    /**
     * 
     * @type {number}
     * @memberof SessionPlanStrengthSetData
     */
    repetitionCount: number;
    /**
     * 
     * @type {number}
     * @memberof SessionPlanStrengthSetData
     */
    resistance: number;
    /**
     * 
     * @type {ForceUnit}
     * @memberof SessionPlanStrengthSetData
     */
    forceUnit: ForceUnit;
    /**
     * 
     * @type {StrengthExerciseData}
     * @memberof SessionPlanStrengthSetData
     */
    strengthExercise?: StrengthExerciseData;
    /**
     * 
     * @type {StrengthMachineData}
     * @memberof SessionPlanStrengthSetData
     */
    strengthMachine?: StrengthMachineData;
}

/**
 * Check if a given object implements the SessionPlanStrengthSetData interface.
 */
export function instanceOfSessionPlanStrengthSetData(value: object): value is SessionPlanStrengthSetData {
    if (!('repetitionCount' in value) || value['repetitionCount'] === undefined) return false;
    if (!('resistance' in value) || value['resistance'] === undefined) return false;
    if (!('forceUnit' in value) || value['forceUnit'] === undefined) return false;
    return true;
}

export function SessionPlanStrengthSetDataFromJSON(json: any): SessionPlanStrengthSetData {
    return SessionPlanStrengthSetDataFromJSONTyped(json, false);
}

export function SessionPlanStrengthSetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPlanStrengthSetData {
    if (json == null) {
        return json;
    }
    return {
        
        'repetitionCount': json['repetitionCount'],
        'resistance': json['resistance'],
        'forceUnit': ForceUnitFromJSON(json['forceUnit']),
        'strengthExercise': json['strengthExercise'] == null ? undefined : StrengthExerciseDataFromJSON(json['strengthExercise']),
        'strengthMachine': json['strengthMachine'] == null ? undefined : StrengthMachineDataFromJSON(json['strengthMachine']),
    };
}

export function SessionPlanStrengthSetDataToJSON(value?: SessionPlanStrengthSetData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'repetitionCount': value['repetitionCount'],
        'resistance': value['resistance'],
        'forceUnit': ForceUnitToJSON(value['forceUnit']),
        'strengthExercise': StrengthExerciseDataToJSON(value['strengthExercise']),
        'strengthMachine': StrengthMachineDataToJSON(value['strengthMachine']),
    };
}

