/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SixRepTestData
 */
export interface SixRepTestData {
    /**
     * 
     * @type {number}
     * @memberof SixRepTestData
     */
    forceAtPeakPower: number;
    /**
     * 
     * @type {number}
     * @memberof SixRepTestData
     */
    lowerRepIndex: number;
    /**
     * 
     * @type {number}
     * @memberof SixRepTestData
     */
    upperRepIndex: number;
}

/**
 * Check if a given object implements the SixRepTestData interface.
 */
export function instanceOfSixRepTestData(value: object): value is SixRepTestData {
    if (!('forceAtPeakPower' in value) || value['forceAtPeakPower'] === undefined) return false;
    if (!('lowerRepIndex' in value) || value['lowerRepIndex'] === undefined) return false;
    if (!('upperRepIndex' in value) || value['upperRepIndex'] === undefined) return false;
    return true;
}

export function SixRepTestDataFromJSON(json: any): SixRepTestData {
    return SixRepTestDataFromJSONTyped(json, false);
}

export function SixRepTestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SixRepTestData {
    if (json == null) {
        return json;
    }
    return {
        
        'forceAtPeakPower': json['forceAtPeakPower'],
        'lowerRepIndex': json['lowerRepIndex'],
        'upperRepIndex': json['upperRepIndex'],
    };
}

export function SixRepTestDataToJSON(value?: SixRepTestData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'forceAtPeakPower': value['forceAtPeakPower'],
        'lowerRepIndex': value['lowerRepIndex'],
        'upperRepIndex': value['upperRepIndex'],
    };
}

