/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExerciseAliasData } from './ExerciseAliasData';
import {
    ExerciseAliasDataFromJSON,
    ExerciseAliasDataFromJSONTyped,
    ExerciseAliasDataToJSON,
} from './ExerciseAliasData';
import type { MuscleData } from './MuscleData';
import {
    MuscleDataFromJSON,
    MuscleDataFromJSONTyped,
    MuscleDataToJSON,
} from './MuscleData';
import type { StrengthExerciseCategory } from './StrengthExerciseCategory';
import {
    StrengthExerciseCategoryFromJSON,
    StrengthExerciseCategoryFromJSONTyped,
    StrengthExerciseCategoryToJSON,
} from './StrengthExerciseCategory';
import type { StrengthExerciseMovement } from './StrengthExerciseMovement';
import {
    StrengthExerciseMovementFromJSON,
    StrengthExerciseMovementFromJSONTyped,
    StrengthExerciseMovementToJSON,
} from './StrengthExerciseMovement';
import type { StrengthExerciseMovementDEP } from './StrengthExerciseMovementDEP';
import {
    StrengthExerciseMovementDEPFromJSON,
    StrengthExerciseMovementDEPFromJSONTyped,
    StrengthExerciseMovementDEPToJSON,
} from './StrengthExerciseMovementDEP';
import type { StrengthExercisePlane } from './StrengthExercisePlane';
import {
    StrengthExercisePlaneFromJSON,
    StrengthExercisePlaneFromJSONTyped,
    StrengthExercisePlaneToJSON,
} from './StrengthExercisePlane';
import type { StrengthExerciseVariantData } from './StrengthExerciseVariantData';
import {
    StrengthExerciseVariantDataFromJSON,
    StrengthExerciseVariantDataFromJSONTyped,
    StrengthExerciseVariantDataToJSON,
} from './StrengthExerciseVariantData';
import type { StrengthMachineData } from './StrengthMachineData';
import {
    StrengthMachineDataFromJSON,
    StrengthMachineDataFromJSONTyped,
    StrengthMachineDataToJSON,
} from './StrengthMachineData';

/**
 * 
 * @export
 * @interface StrengthExerciseData
 */
export interface StrengthExerciseData {
    /**
     * 
     * @type {number}
     * @memberof StrengthExerciseData
     */
    id: number;
    /**
     * 
     * @type {StrengthExerciseCategory}
     * @memberof StrengthExerciseData
     */
    category: StrengthExerciseCategory;
    /**
     * 
     * @type {StrengthExerciseMovementDEP}
     * @memberof StrengthExerciseData
     */
    movement?: StrengthExerciseMovementDEP;
    /**
     * 
     * @type {StrengthExerciseMovement}
     * @memberof StrengthExerciseData
     */
    humanMovement?: StrengthExerciseMovement;
    /**
     * 
     * @type {StrengthExercisePlane}
     * @memberof StrengthExerciseData
     */
    plane: StrengthExercisePlane;
    /**
     * 
     * @type {ExerciseAliasData}
     * @memberof StrengthExerciseData
     */
    defaultExerciseAlias?: ExerciseAliasData;
    /**
     * 
     * @type {Array<ExerciseAliasData>}
     * @memberof StrengthExerciseData
     */
    exerciseAliases?: Array<ExerciseAliasData>;
    /**
     * 
     * @type {Array<StrengthExerciseVariantData>}
     * @memberof StrengthExerciseData
     */
    strengthExerciseVariants?: Array<StrengthExerciseVariantData>;
    /**
     * 
     * @type {Array<MuscleData>}
     * @memberof StrengthExerciseData
     */
    strengthExerciseMuscles?: Array<MuscleData>;
    /**
     * 
     * @type {Array<StrengthMachineData>}
     * @memberof StrengthExerciseData
     */
    strengthMachines?: Array<StrengthMachineData>;
}

/**
 * Check if a given object implements the StrengthExerciseData interface.
 */
export function instanceOfStrengthExerciseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "plane" in value;

    return isInstance;
}

export function StrengthExerciseDataFromJSON(json: any): StrengthExerciseData {
    return StrengthExerciseDataFromJSONTyped(json, false);
}

export function StrengthExerciseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrengthExerciseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': StrengthExerciseCategoryFromJSON(json['category']),
        'movement': !exists(json, 'movement') ? undefined : StrengthExerciseMovementDEPFromJSON(json['movement']),
        'humanMovement': !exists(json, 'humanMovement') ? undefined : StrengthExerciseMovementFromJSON(json['humanMovement']),
        'plane': StrengthExercisePlaneFromJSON(json['plane']),
        'defaultExerciseAlias': !exists(json, 'defaultExerciseAlias') ? undefined : ExerciseAliasDataFromJSON(json['defaultExerciseAlias']),
        'exerciseAliases': !exists(json, 'exerciseAliases') ? undefined : ((json['exerciseAliases'] as Array<any>).map(ExerciseAliasDataFromJSON)),
        'strengthExerciseVariants': !exists(json, 'strengthExerciseVariants') ? undefined : ((json['strengthExerciseVariants'] as Array<any>).map(StrengthExerciseVariantDataFromJSON)),
        'strengthExerciseMuscles': !exists(json, 'strengthExerciseMuscles') ? undefined : ((json['strengthExerciseMuscles'] as Array<any>).map(MuscleDataFromJSON)),
        'strengthMachines': !exists(json, 'strengthMachines') ? undefined : ((json['strengthMachines'] as Array<any>).map(StrengthMachineDataFromJSON)),
    };
}

export function StrengthExerciseDataToJSON(value?: StrengthExerciseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'category': StrengthExerciseCategoryToJSON(value.category),
        'movement': StrengthExerciseMovementDEPToJSON(value.movement),
        'humanMovement': StrengthExerciseMovementToJSON(value.humanMovement),
        'plane': StrengthExercisePlaneToJSON(value.plane),
        'defaultExerciseAlias': ExerciseAliasDataToJSON(value.defaultExerciseAlias),
        'exerciseAliases': value.exerciseAliases === undefined ? undefined : ((value.exerciseAliases as Array<any>).map(ExerciseAliasDataToJSON)),
        'strengthExerciseVariants': value.strengthExerciseVariants === undefined ? undefined : ((value.strengthExerciseVariants as Array<any>).map(StrengthExerciseVariantDataToJSON)),
        'strengthExerciseMuscles': value.strengthExerciseMuscles === undefined ? undefined : ((value.strengthExerciseMuscles as Array<any>).map(MuscleDataToJSON)),
        'strengthMachines': value.strengthMachines === undefined ? undefined : ((value.strengthMachines as Array<any>).map(StrengthMachineDataToJSON)),
    };
}

