/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const StrengthMachineDataSetSorting = {
    id: 'id',
    completedAt: 'completedAt'
} as const;
export type StrengthMachineDataSetSorting =
        | 'id' 
        | 'completedAt' 
;


export function instanceOfStrengthMachineDataSetSorting(value: unknown): boolean {
    return (Object.values(StrengthMachineDataSetSorting) as unknown[]).includes(value);
}

export function StrengthMachineDataSetSortingFromJSON(json: unknown): StrengthMachineDataSetSorting {
    return StrengthMachineDataSetSortingFromJSONTyped(json, false);
}

export function StrengthMachineDataSetSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): StrengthMachineDataSetSorting {
    return json as StrengthMachineDataSetSorting;
}

export function StrengthMachineDataSetSortingToJSON(value?: StrengthMachineDataSetSorting | null): StrengthMachineDataSetSorting | null | undefined {
    return value;
}

