/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MuscleData } from './MuscleData';
import {
    MuscleDataFromJSON,
    MuscleDataFromJSONTyped,
    MuscleDataToJSON,
} from './MuscleData';
import type { StrengthExerciseCategory } from './StrengthExerciseCategory';
import {
    StrengthExerciseCategoryFromJSON,
    StrengthExerciseCategoryFromJSONTyped,
    StrengthExerciseCategoryToJSON,
} from './StrengthExerciseCategory';
import type { ExerciseAliasData } from './ExerciseAliasData';
import {
    ExerciseAliasDataFromJSON,
    ExerciseAliasDataFromJSONTyped,
    ExerciseAliasDataToJSON,
} from './ExerciseAliasData';
import type { StrengthExerciseMovementDEP } from './StrengthExerciseMovementDEP';
import {
    StrengthExerciseMovementDEPFromJSON,
    StrengthExerciseMovementDEPFromJSONTyped,
    StrengthExerciseMovementDEPToJSON,
} from './StrengthExerciseMovementDEP';
import type { StrengthExercisePlane } from './StrengthExercisePlane';
import {
    StrengthExercisePlaneFromJSON,
    StrengthExercisePlaneFromJSONTyped,
    StrengthExercisePlaneToJSON,
} from './StrengthExercisePlane';
import type { StrengthMachineData } from './StrengthMachineData';
import {
    StrengthMachineDataFromJSON,
    StrengthMachineDataFromJSONTyped,
    StrengthMachineDataToJSON,
} from './StrengthMachineData';
import type { StrengthExerciseMovement } from './StrengthExerciseMovement';
import {
    StrengthExerciseMovementFromJSON,
    StrengthExerciseMovementFromJSONTyped,
    StrengthExerciseMovementToJSON,
} from './StrengthExerciseMovement';
import type { StrengthExerciseVariantData } from './StrengthExerciseVariantData';
import {
    StrengthExerciseVariantDataFromJSON,
    StrengthExerciseVariantDataFromJSONTyped,
    StrengthExerciseVariantDataToJSON,
} from './StrengthExerciseVariantData';

/**
 * 
 * @export
 * @interface StrengthExerciseData
 */
export interface StrengthExerciseData {
    /**
     * 
     * @type {number}
     * @memberof StrengthExerciseData
     */
    id: number;
    /**
     * 
     * @type {StrengthExerciseCategory}
     * @memberof StrengthExerciseData
     */
    category: StrengthExerciseCategory;
    /**
     * 
     * @type {StrengthExerciseMovementDEP}
     * @memberof StrengthExerciseData
     */
    movement?: StrengthExerciseMovementDEP;
    /**
     * 
     * @type {StrengthExerciseMovement}
     * @memberof StrengthExerciseData
     */
    humanMovement?: StrengthExerciseMovement;
    /**
     * 
     * @type {StrengthExercisePlane}
     * @memberof StrengthExerciseData
     */
    plane: StrengthExercisePlane;
    /**
     * 
     * @type {ExerciseAliasData}
     * @memberof StrengthExerciseData
     */
    defaultExerciseAlias?: ExerciseAliasData;
    /**
     * 
     * @type {Array<ExerciseAliasData>}
     * @memberof StrengthExerciseData
     */
    exerciseAliases?: Array<ExerciseAliasData>;
    /**
     * 
     * @type {Array<StrengthExerciseVariantData>}
     * @memberof StrengthExerciseData
     */
    strengthExerciseVariants?: Array<StrengthExerciseVariantData>;
    /**
     * 
     * @type {Array<MuscleData>}
     * @memberof StrengthExerciseData
     */
    strengthExerciseMuscles?: Array<MuscleData>;
    /**
     * 
     * @type {Array<StrengthMachineData>}
     * @memberof StrengthExerciseData
     */
    strengthMachines?: Array<StrengthMachineData>;
}

/**
 * Check if a given object implements the StrengthExerciseData interface.
 */
export function instanceOfStrengthExerciseData(value: object): value is StrengthExerciseData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('plane' in value) || value['plane'] === undefined) return false;
    return true;
}

export function StrengthExerciseDataFromJSON(json: any): StrengthExerciseData {
    return StrengthExerciseDataFromJSONTyped(json, false);
}

export function StrengthExerciseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrengthExerciseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': StrengthExerciseCategoryFromJSON(json['category']),
        'movement': json['movement'] == null ? undefined : StrengthExerciseMovementDEPFromJSON(json['movement']),
        'humanMovement': json['humanMovement'] == null ? undefined : StrengthExerciseMovementFromJSON(json['humanMovement']),
        'plane': StrengthExercisePlaneFromJSON(json['plane']),
        'defaultExerciseAlias': json['defaultExerciseAlias'] == null ? undefined : ExerciseAliasDataFromJSON(json['defaultExerciseAlias']),
        'exerciseAliases': json['exerciseAliases'] == null ? undefined : ((json['exerciseAliases'] as Array<any>).map(ExerciseAliasDataFromJSON)),
        'strengthExerciseVariants': json['strengthExerciseVariants'] == null ? undefined : ((json['strengthExerciseVariants'] as Array<any>).map(StrengthExerciseVariantDataFromJSON)),
        'strengthExerciseMuscles': json['strengthExerciseMuscles'] == null ? undefined : ((json['strengthExerciseMuscles'] as Array<any>).map(MuscleDataFromJSON)),
        'strengthMachines': json['strengthMachines'] == null ? undefined : ((json['strengthMachines'] as Array<any>).map(StrengthMachineDataFromJSON)),
    };
}

export function StrengthExerciseDataToJSON(value?: StrengthExerciseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'category': StrengthExerciseCategoryToJSON(value['category']),
        'movement': StrengthExerciseMovementDEPToJSON(value['movement']),
        'humanMovement': StrengthExerciseMovementToJSON(value['humanMovement']),
        'plane': StrengthExercisePlaneToJSON(value['plane']),
        'defaultExerciseAlias': ExerciseAliasDataToJSON(value['defaultExerciseAlias']),
        'exerciseAliases': value['exerciseAliases'] == null ? undefined : ((value['exerciseAliases'] as Array<any>).map(ExerciseAliasDataToJSON)),
        'strengthExerciseVariants': value['strengthExerciseVariants'] == null ? undefined : ((value['strengthExerciseVariants'] as Array<any>).map(StrengthExerciseVariantDataToJSON)),
        'strengthExerciseMuscles': value['strengthExerciseMuscles'] == null ? undefined : ((value['strengthExerciseMuscles'] as Array<any>).map(MuscleDataToJSON)),
        'strengthMachines': value['strengthMachines'] == null ? undefined : ((value['strengthMachines'] as Array<any>).map(StrengthMachineDataToJSON)),
    };
}

