/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StrengthMachineDataSetSorting } from './StrengthMachineDataSetSorting';
import {
    StrengthMachineDataSetSortingFromJSON,
    StrengthMachineDataSetSortingFromJSONTyped,
    StrengthMachineDataSetSortingToJSON,
} from './StrengthMachineDataSetSorting';

/**
 * 
 * @export
 * @interface StrengthMachineDataSetListResponseMeta
 */
export interface StrengthMachineDataSetListResponseMeta {
    /**
     * 
     * @type {string}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    query?: string;
    /**
     * 
     * @type {Date}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    to?: Date;
    /**
     * 
     * @type {StrengthMachineDataSetSorting}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    sort: StrengthMachineDataSetSorting;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    userId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the StrengthMachineDataSetListResponseMeta interface.
 */
export function instanceOfStrengthMachineDataSetListResponseMeta(value: object): value is StrengthMachineDataSetListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function StrengthMachineDataSetListResponseMetaFromJSON(json: any): StrengthMachineDataSetListResponseMeta {
    return StrengthMachineDataSetListResponseMetaFromJSONTyped(json, false);
}

export function StrengthMachineDataSetListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrengthMachineDataSetListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'sort': StrengthMachineDataSetSortingFromJSON(json['sort']),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function StrengthMachineDataSetListResponseMetaToJSON(value?: StrengthMachineDataSetListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': value['query'],
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
        'sort': StrengthMachineDataSetSortingToJSON(value['sort']),
        'userId': value['userId'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

