/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResistancePrecision } from './ResistancePrecision';
import {
    ResistancePrecisionFromJSON,
    ResistancePrecisionFromJSONTyped,
    ResistancePrecisionToJSON,
} from './ResistancePrecision';
import type { A400DataSetData } from './A400DataSetData';
import {
    A400DataSetDataFromJSON,
    A400DataSetDataFromJSONTyped,
    A400DataSetDataToJSON,
} from './A400DataSetData';
import type { A500DataSetData } from './A500DataSetData';
import {
    A500DataSetDataFromJSON,
    A500DataSetDataFromJSONTyped,
    A500DataSetDataToJSON,
} from './A500DataSetData';
import type { ForceUnit } from './ForceUnit';
import {
    ForceUnitFromJSON,
    ForceUnitFromJSONTyped,
    ForceUnitToJSON,
} from './ForceUnit';
import type { StrengthMachineData } from './StrengthMachineData';
import {
    StrengthMachineDataFromJSON,
    StrengthMachineDataFromJSONTyped,
    StrengthMachineDataToJSON,
} from './StrengthMachineData';
import type { ProfileData } from './ProfileData';
import {
    ProfileDataFromJSON,
    ProfileDataFromJSONTyped,
    ProfileDataToJSON,
} from './ProfileData';
import type { SessionData } from './SessionData';
import {
    SessionDataFromJSON,
    SessionDataFromJSONTyped,
    SessionDataToJSON,
} from './SessionData';
import type { FacilityStrengthMachineData } from './FacilityStrengthMachineData';
import {
    FacilityStrengthMachineDataFromJSON,
    FacilityStrengthMachineDataFromJSONTyped,
    FacilityStrengthMachineDataToJSON,
} from './FacilityStrengthMachineData';
import type { StrengthExerciseData } from './StrengthExerciseData';
import {
    StrengthExerciseDataFromJSON,
    StrengthExerciseDataFromJSONTyped,
    StrengthExerciseDataToJSON,
} from './StrengthExerciseData';
import type { StrengthMachineDataSetTestData } from './StrengthMachineDataSetTestData';
import {
    StrengthMachineDataSetTestDataFromJSON,
    StrengthMachineDataSetTestDataFromJSONTyped,
    StrengthMachineDataSetTestDataToJSON,
} from './StrengthMachineDataSetTestData';

/**
 * 
 * @export
 * @interface StrengthMachineDataSetData
 */
export interface StrengthMachineDataSetData {
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    userId: number;
    /**
     * 
     * @type {Date}
     * @memberof StrengthMachineDataSetData
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof StrengthMachineDataSetData
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof StrengthMachineDataSetData
     */
    serial: string;
    /**
     * 
     * @type {Date}
     * @memberof StrengthMachineDataSetData
     */
    completedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    chest?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    rom1?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    rom2?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    seat?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    resistance?: number;
    /**
     * 
     * @type {ResistancePrecision}
     * @memberof StrengthMachineDataSetData
     */
    resistancePrecision: ResistancePrecision;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    repetitionCount: number;
    /**
     * 
     * @type {ForceUnit}
     * @memberof StrengthMachineDataSetData
     */
    forceUnit?: ForceUnit;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    peakPower?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    peakVelocity?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    work?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    distance?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    addedWeight?: number;
    /**
     * 
     * @type {string}
     * @memberof StrengthMachineDataSetData
     */
    clientSetId?: string;
    /**
     * 
     * @type {number}
     * @memberof StrengthMachineDataSetData
     */
    setNumber?: number;
    /**
     * 
     * @type {Date}
     * @memberof StrengthMachineDataSetData
     */
    startedAt?: Date;
    /**
     * 
     * @type {StrengthMachineDataSetTestData}
     * @memberof StrengthMachineDataSetData
     */
    test?: StrengthMachineDataSetTestData;
    /**
     * 
     * @type {StrengthMachineData}
     * @memberof StrengthMachineDataSetData
     */
    strengthMachine?: StrengthMachineData;
    /**
     * 
     * @type {StrengthExerciseData}
     * @memberof StrengthMachineDataSetData
     */
    strengthExercise?: StrengthExerciseData;
    /**
     * 
     * @type {A500DataSetData}
     * @memberof StrengthMachineDataSetData
     */
    a500DataSet?: A500DataSetData;
    /**
     * 
     * @type {A400DataSetData}
     * @memberof StrengthMachineDataSetData
     */
    a400DataSet?: A400DataSetData;
    /**
     * 
     * @type {SessionData}
     * @memberof StrengthMachineDataSetData
     */
    session?: SessionData;
    /**
     * 
     * @type {ProfileData}
     * @memberof StrengthMachineDataSetData
     */
    profile?: ProfileData;
    /**
     * 
     * @type {FacilityStrengthMachineData}
     * @memberof StrengthMachineDataSetData
     */
    facilityStrengthMachine?: FacilityStrengthMachineData;
}

/**
 * Check if a given object implements the StrengthMachineDataSetData interface.
 */
export function instanceOfStrengthMachineDataSetData(value: object): value is StrengthMachineDataSetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('serial' in value) || value['serial'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('resistancePrecision' in value) || value['resistancePrecision'] === undefined) return false;
    if (!('repetitionCount' in value) || value['repetitionCount'] === undefined) return false;
    return true;
}

export function StrengthMachineDataSetDataFromJSON(json: any): StrengthMachineDataSetData {
    return StrengthMachineDataSetDataFromJSONTyped(json, false);
}

export function StrengthMachineDataSetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrengthMachineDataSetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'updatedAt': (new Date(json['updatedAt'])),
        'version': json['version'],
        'serial': json['serial'],
        'completedAt': (new Date(json['completedAt'])),
        'chest': json['chest'] == null ? undefined : json['chest'],
        'rom1': json['rom1'] == null ? undefined : json['rom1'],
        'rom2': json['rom2'] == null ? undefined : json['rom2'],
        'seat': json['seat'] == null ? undefined : json['seat'],
        'resistance': json['resistance'] == null ? undefined : json['resistance'],
        'resistancePrecision': ResistancePrecisionFromJSON(json['resistancePrecision']),
        'repetitionCount': json['repetitionCount'],
        'forceUnit': json['forceUnit'] == null ? undefined : ForceUnitFromJSON(json['forceUnit']),
        'peakPower': json['peakPower'] == null ? undefined : json['peakPower'],
        'peakVelocity': json['peakVelocity'] == null ? undefined : json['peakVelocity'],
        'work': json['work'] == null ? undefined : json['work'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'addedWeight': json['addedWeight'] == null ? undefined : json['addedWeight'],
        'clientSetId': json['clientSetId'] == null ? undefined : json['clientSetId'],
        'setNumber': json['setNumber'] == null ? undefined : json['setNumber'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'test': json['test'] == null ? undefined : StrengthMachineDataSetTestDataFromJSON(json['test']),
        'strengthMachine': json['strengthMachine'] == null ? undefined : StrengthMachineDataFromJSON(json['strengthMachine']),
        'strengthExercise': json['strengthExercise'] == null ? undefined : StrengthExerciseDataFromJSON(json['strengthExercise']),
        'a500DataSet': json['a500DataSet'] == null ? undefined : A500DataSetDataFromJSON(json['a500DataSet']),
        'a400DataSet': json['a400DataSet'] == null ? undefined : A400DataSetDataFromJSON(json['a400DataSet']),
        'session': json['session'] == null ? undefined : SessionDataFromJSON(json['session']),
        'profile': json['profile'] == null ? undefined : ProfileDataFromJSON(json['profile']),
        'facilityStrengthMachine': json['facilityStrengthMachine'] == null ? undefined : FacilityStrengthMachineDataFromJSON(json['facilityStrengthMachine']),
    };
}

export function StrengthMachineDataSetDataToJSON(value?: StrengthMachineDataSetData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'updatedAt': ((value['updatedAt']).toISOString()),
        'version': value['version'],
        'serial': value['serial'],
        'completedAt': ((value['completedAt']).toISOString()),
        'chest': value['chest'],
        'rom1': value['rom1'],
        'rom2': value['rom2'],
        'seat': value['seat'],
        'resistance': value['resistance'],
        'resistancePrecision': ResistancePrecisionToJSON(value['resistancePrecision']),
        'repetitionCount': value['repetitionCount'],
        'forceUnit': ForceUnitToJSON(value['forceUnit']),
        'peakPower': value['peakPower'],
        'peakVelocity': value['peakVelocity'],
        'work': value['work'],
        'distance': value['distance'],
        'addedWeight': value['addedWeight'],
        'clientSetId': value['clientSetId'],
        'setNumber': value['setNumber'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'test': StrengthMachineDataSetTestDataToJSON(value['test']),
        'strengthMachine': StrengthMachineDataToJSON(value['strengthMachine']),
        'strengthExercise': StrengthExerciseDataToJSON(value['strengthExercise']),
        'a500DataSet': A500DataSetDataToJSON(value['a500DataSet']),
        'a400DataSet': A400DataSetDataToJSON(value['a400DataSet']),
        'session': SessionDataToJSON(value['session']),
        'profile': ProfileDataToJSON(value['profile']),
        'facilityStrengthMachine': FacilityStrengthMachineDataToJSON(value['facilityStrengthMachine']),
    };
}

