/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MuscleSorting } from './MuscleSorting';
import {
    MuscleSortingFromJSON,
    MuscleSortingFromJSONTyped,
    MuscleSortingToJSON,
} from './MuscleSorting';
import type { MuscleTargetLevel } from './MuscleTargetLevel';
import {
    MuscleTargetLevelFromJSON,
    MuscleTargetLevelFromJSONTyped,
    MuscleTargetLevelToJSON,
} from './MuscleTargetLevel';

/**
 * 
 * @export
 * @interface StrengthExerciseMuscleListResponseMeta
 */
export interface StrengthExerciseMuscleListResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    strengthExerciseId?: number;
    /**
     * 
     * @type {string}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    muscle?: string;
    /**
     * 
     * @type {MuscleTargetLevel}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    targetLevel?: MuscleTargetLevel;
    /**
     * 
     * @type {MuscleSorting}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    sort: MuscleSorting;
    /**
     * 
     * @type {boolean}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof StrengthExerciseMuscleListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the StrengthExerciseMuscleListResponseMeta interface.
 */
export function instanceOfStrengthExerciseMuscleListResponseMeta(value: object): value is StrengthExerciseMuscleListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function StrengthExerciseMuscleListResponseMetaFromJSON(json: any): StrengthExerciseMuscleListResponseMeta {
    return StrengthExerciseMuscleListResponseMetaFromJSONTyped(json, false);
}

export function StrengthExerciseMuscleListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrengthExerciseMuscleListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'strengthExerciseId': json['strengthExerciseId'] == null ? undefined : json['strengthExerciseId'],
        'muscle': json['muscle'] == null ? undefined : json['muscle'],
        'targetLevel': json['targetLevel'] == null ? undefined : MuscleTargetLevelFromJSON(json['targetLevel']),
        'sort': MuscleSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function StrengthExerciseMuscleListResponseMetaToJSON(value?: StrengthExerciseMuscleListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'strengthExerciseId': value['strengthExerciseId'],
        'muscle': value['muscle'],
        'targetLevel': MuscleTargetLevelToJSON(value['targetLevel']),
        'sort': MuscleSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

