/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const TestSide = {
    left: 'left',
    right: 'right',
    both: 'both'
} as const;
export type TestSide =
        | 'left' 
        | 'right' 
        | 'both' 
;


export function instanceOfTestSide(value: unknown): boolean {
    return (Object.values(TestSide) as unknown[]).includes(value);
}

export function TestSideFromJSON(json: unknown): TestSide {
    return TestSideFromJSONTyped(json, false);
}

export function TestSideFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): TestSide {
    return json as TestSide;
}

export function TestSideToJSON(value?: TestSide | null): TestSide | null | undefined {
    return value;
}

