/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeResponse
 */
export interface TimeResponse {
    /**
     * 
     * @type {string}
     * @memberof TimeResponse
     */
    isoDate: string;
    /**
     * 
     * @type {number}
     * @memberof TimeResponse
     */
    unixOffset: number;
}

/**
 * Check if a given object implements the TimeResponse interface.
 */
export function instanceOfTimeResponse(value: object): value is TimeResponse {
    if (!('isoDate' in value) || value['isoDate'] === undefined) return false;
    if (!('unixOffset' in value) || value['unixOffset'] === undefined) return false;
    return true;
}

export function TimeResponseFromJSON(json: any): TimeResponse {
    return TimeResponseFromJSONTyped(json, false);
}

export function TimeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isoDate': json['isoDate'],
        'unixOffset': json['unixOffset'],
    };
}

export function TimeResponseToJSON(value?: TimeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isoDate': value['isoDate'],
        'unixOffset': value['unixOffset'],
    };
}

