/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSessionDisplayConfigurationData } from './UserSessionDisplayConfigurationData';
import {
    UserSessionDisplayConfigurationDataFromJSON,
    UserSessionDisplayConfigurationDataFromJSONTyped,
    UserSessionDisplayConfigurationDataToJSON,
} from './UserSessionDisplayConfigurationData';

/**
 * 
 * @export
 * @interface UserSessionDisplayConfigurationResponse
 */
export interface UserSessionDisplayConfigurationResponse {
    /**
     * 
     * @type {UserSessionDisplayConfigurationData}
     * @memberof UserSessionDisplayConfigurationResponse
     */
    userSessionDisplayConfiguration: UserSessionDisplayConfigurationData;
    /**
     * 
     * @type {string}
     * @memberof UserSessionDisplayConfigurationResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSessionDisplayConfigurationResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the UserSessionDisplayConfigurationResponse interface.
 */
export function instanceOfUserSessionDisplayConfigurationResponse(value: object): value is UserSessionDisplayConfigurationResponse {
    if (!('userSessionDisplayConfiguration' in value) || value['userSessionDisplayConfiguration'] === undefined) return false;
    return true;
}

export function UserSessionDisplayConfigurationResponseFromJSON(json: any): UserSessionDisplayConfigurationResponse {
    return UserSessionDisplayConfigurationResponseFromJSONTyped(json, false);
}

export function UserSessionDisplayConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSessionDisplayConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userSessionDisplayConfiguration': UserSessionDisplayConfigurationDataFromJSON(json['userSessionDisplayConfiguration']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function UserSessionDisplayConfigurationResponseToJSON(value?: UserSessionDisplayConfigurationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userSessionDisplayConfiguration': UserSessionDisplayConfigurationDataToJSON(value['userSessionDisplayConfiguration']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

