/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserApplicationAuthorizationMeta
 */
export interface UserApplicationAuthorizationMeta {
    /**
     * 
     * @type {number}
     * @memberof UserApplicationAuthorizationMeta
     */
    developmentAccountId: number;
    /**
     * 
     * @type {number}
     * @memberof UserApplicationAuthorizationMeta
     */
    applicationId: number;
    /**
     * 
     * @type {string}
     * @memberof UserApplicationAuthorizationMeta
     */
    sort?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserApplicationAuthorizationMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserApplicationAuthorizationMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserApplicationAuthorizationMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof UserApplicationAuthorizationMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the UserApplicationAuthorizationMeta interface.
 */
export function instanceOfUserApplicationAuthorizationMeta(value: object): value is UserApplicationAuthorizationMeta {
    if (!('developmentAccountId' in value) || value['developmentAccountId'] === undefined) return false;
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    return true;
}

export function UserApplicationAuthorizationMetaFromJSON(json: any): UserApplicationAuthorizationMeta {
    return UserApplicationAuthorizationMetaFromJSONTyped(json, false);
}

export function UserApplicationAuthorizationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApplicationAuthorizationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'developmentAccountId': json['developmentAccountId'],
        'applicationId': json['applicationId'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function UserApplicationAuthorizationMetaToJSON(value?: UserApplicationAuthorizationMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'developmentAccountId': value['developmentAccountId'],
        'applicationId': value['applicationId'],
        'sort': value['sort'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

