/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Value
 */
export interface Value {
    /**
     * 
     * @type {number}
     * @memberof Value
     */
    value: number;
    /**
     * 
     * @type {boolean}
     * @memberof Value
     */
    isAboveDropOff?: boolean;
}

/**
 * Check if a given object implements the Value interface.
 */
export function instanceOfValue(value: object): value is Value {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ValueFromJSON(json: any): Value {
    return ValueFromJSONTyped(json, false);
}

export function ValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): Value {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'isAboveDropOff': json['isAboveDropOff'] == null ? undefined : json['isAboveDropOff'],
    };
}

export function ValueToJSON(value?: Value | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
        'isAboveDropOff': value['isAboveDropOff'],
    };
}

