/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VelocityRegression
 */
export interface VelocityRegression {
    /**
     * 
     * @type {number}
     * @memberof VelocityRegression
     */
    m: number;
    /**
     * 
     * @type {number}
     * @memberof VelocityRegression
     */
    b: number;
}

/**
 * Check if a given object implements the VelocityRegression interface.
 */
export function instanceOfVelocityRegression(value: object): value is VelocityRegression {
    if (!('m' in value) || value['m'] === undefined) return false;
    if (!('b' in value) || value['b'] === undefined) return false;
    return true;
}

export function VelocityRegressionFromJSON(json: any): VelocityRegression {
    return VelocityRegressionFromJSONTyped(json, false);
}

export function VelocityRegressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): VelocityRegression {
    if (json == null) {
        return json;
    }
    return {
        
        'm': json['m'],
        'b': json['b'],
    };
}

export function VelocityRegressionToJSON(value?: VelocityRegression | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'm': value['m'],
        'b': value['b'],
    };
}

