/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WeightMeasurementData } from './WeightMeasurementData';
import {
    WeightMeasurementDataFromJSON,
    WeightMeasurementDataFromJSONTyped,
    WeightMeasurementDataToJSON,
} from './WeightMeasurementData';

/**
 * 
 * @export
 * @interface WeightMeasurementResponse
 */
export interface WeightMeasurementResponse {
    /**
     * 
     * @type {WeightMeasurementData}
     * @memberof WeightMeasurementResponse
     */
    weightMeasurement: WeightMeasurementData;
    /**
     * 
     * @type {string}
     * @memberof WeightMeasurementResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof WeightMeasurementResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the WeightMeasurementResponse interface.
 */
export function instanceOfWeightMeasurementResponse(value: object): value is WeightMeasurementResponse {
    if (!('weightMeasurement' in value) || value['weightMeasurement'] === undefined) return false;
    return true;
}

export function WeightMeasurementResponseFromJSON(json: any): WeightMeasurementResponse {
    return WeightMeasurementResponseFromJSONTyped(json, false);
}

export function WeightMeasurementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeightMeasurementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'weightMeasurement': WeightMeasurementDataFromJSON(json['weightMeasurement']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function WeightMeasurementResponseToJSON(value?: WeightMeasurementResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'weightMeasurement': WeightMeasurementDataToJSON(value['weightMeasurement']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

