/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MotionDataPoint } from './MotionDataPoint';
import {
    MotionDataPointFromJSON,
    MotionDataPointFromJSONTyped,
    MotionDataPointToJSON,
} from './MotionDataPoint';

/**
 * 
 * @export
 * @interface WorkoutSetPositionDataEvent
 */
export interface WorkoutSetPositionDataEvent {
    /**
     * 
     * @type {number}
     * @memberof WorkoutSetPositionDataEvent
     */
    timeSinceEpoch: number;
    /**
     * 
     * @type {number}
     * @memberof WorkoutSetPositionDataEvent
     */
    completedAt: number;
    /**
     * 
     * @type {MotionDataPoint}
     * @memberof WorkoutSetPositionDataEvent
     */
    left: MotionDataPoint;
    /**
     * 
     * @type {MotionDataPoint}
     * @memberof WorkoutSetPositionDataEvent
     */
    right: MotionDataPoint;
}

/**
 * Check if a given object implements the WorkoutSetPositionDataEvent interface.
 */
export function instanceOfWorkoutSetPositionDataEvent(value: object): value is WorkoutSetPositionDataEvent {
    if (!('timeSinceEpoch' in value) || value['timeSinceEpoch'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('left' in value) || value['left'] === undefined) return false;
    if (!('right' in value) || value['right'] === undefined) return false;
    return true;
}

export function WorkoutSetPositionDataEventFromJSON(json: any): WorkoutSetPositionDataEvent {
    return WorkoutSetPositionDataEventFromJSONTyped(json, false);
}

export function WorkoutSetPositionDataEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutSetPositionDataEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'timeSinceEpoch': json['timeSinceEpoch'],
        'completedAt': json['completedAt'],
        'left': MotionDataPointFromJSON(json['left']),
        'right': MotionDataPointFromJSON(json['right']),
    };
}

export function WorkoutSetPositionDataEventToJSON(value?: WorkoutSetPositionDataEvent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'timeSinceEpoch': value['timeSinceEpoch'],
        'completedAt': value['completedAt'],
        'left': MotionDataPointToJSON(value['left']),
        'right': MotionDataPointToJSON(value['right']),
    };
}

